//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		achievements_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class achievements_DB
    {

        #region "Private methods"

        private static achievements_DT FillInfoObject(SqlDataReader dr)
        {

           achievements_DT obj_achievements_DT = new achievements_DT();

           
		obj_achievements_DT.type = dr[achievements_DT.Enum_achievements_DT.type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[achievements_DT.Enum_achievements_DT.type.ToString()]);
		obj_achievements_DT.id = Convert.ToInt32(dr[achievements_DT.Enum_achievements_DT.id.ToString()]);
		obj_achievements_DT.char_id = dr[achievements_DT.Enum_achievements_DT.char_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[achievements_DT.Enum_achievements_DT.char_id.ToString()]);
		obj_achievements_DT.date = dr[achievements_DT.Enum_achievements_DT.date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[achievements_DT.Enum_achievements_DT.date.ToString()]);

           return obj_achievements_DT;
        }

        private static SqlParameter[] GetParameters(achievements_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[4];
           
			

        parms[0] = new SqlParameter(achievements_DT.Enum_achievements_DT.type.ToString(), obj.type);
        

        parms[1] = new SqlParameter(achievements_DT.Enum_achievements_DT.id.ToString(), obj.id);
        parms[1].Direction = ParameterDirection.InputOutput;

        parms[2] = new SqlParameter(achievements_DT.Enum_achievements_DT.char_id.ToString(), obj.char_id);

        parms[3] = new SqlParameter(achievements_DT.Enum_achievements_DT.date.ToString(), obj.date);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(achievements_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "achievements_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int achievements_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "achievements_Delete", achievements_ID);
                return achievements_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "achievements_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static achievements_DT SelectByID(int achievements_ID)
        {
            try
            {
                SqlDataReader drTableName;
                achievements_DT oInfo_achievements_DT = new achievements_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "achievements_Select", achievements_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_achievements_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_achievements_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }


        public static DataTable SelectByCharID(int CharID)
        {
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "achievements_Select_CharID", CharID).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }
       
	#endregion


    }

