//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\maelalfy using Mcit Generator
// Class Name:		architechture_elemnts_DB
// Date Generated:	23-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class architechture_elemnts_DB
    {

        #region "Private methods"

        private static architechture_elemnts_DT FillInfoObject(SqlDataReader dr)
        {

           architechture_elemnts_DT obj_architechture_elemnts_DT = new architechture_elemnts_DT();

           
		obj_architechture_elemnts_DT.id = Convert.ToInt32(dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.id.ToString()]);
		obj_architechture_elemnts_DT.title_ar = dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_ar.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_ar.ToString()]);
		obj_architechture_elemnts_DT.title_en = dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_en.ToString()]);
		obj_architechture_elemnts_DT.title_fr = dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_fr.ToString()]);

           return obj_architechture_elemnts_DT;
        }

        private static SqlParameter[] GetParameters(architechture_elemnts_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[4];
           
			
        

        parms[0] = new SqlParameter(architechture_elemnts_DT.Enum_architechture_elemnts_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_ar.ToString(), obj.title_ar);

        parms[2] = new SqlParameter(architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_en.ToString(), obj.title_en);

        parms[3] = new SqlParameter(architechture_elemnts_DT.Enum_architechture_elemnts_DT.title_fr.ToString(), obj.title_fr);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(architechture_elemnts_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "architechture_elemnts_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int architechture_elemnts_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "architechture_elemnts_Delete", architechture_elemnts_ID);
                return architechture_elemnts_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "architechture_elemnts_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static architechture_elemnts_DT SelectByID(int architechture_elemnts_ID)
        {
            try
            {
              if (architechture_elemnts_ID > 0)
                {
                SqlDataReader drTableName;
                architechture_elemnts_DT oInfo_architechture_elemnts_DT = new architechture_elemnts_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "architechture_elemnts_Select", architechture_elemnts_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_architechture_elemnts_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_architechture_elemnts_DT;
               }
                else
                    return new architechture_elemnts_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

