//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		artifacts_DB
// Date Generated:	08-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class artifacts_DB
    {

        #region "Private methods"

        private static artifacts_DT FillInfoObject(SqlDataReader dr)
        {

           artifacts_DT obj_artifacts_DT = new artifacts_DT();

           
		obj_artifacts_DT.highlight = dr[artifacts_DT.Enum_artifacts_DT.highlight.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.highlight.ToString()]);
		obj_artifacts_DT.highlight_panorama = dr[artifacts_DT.Enum_artifacts_DT.highlight_panorama.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.highlight_panorama.ToString()]);
		obj_artifacts_DT.id = Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.id.ToString()]);
		obj_artifacts_DT.type_id = dr[artifacts_DT.Enum_artifacts_DT.type_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.type_id.ToString()]);
		obj_artifacts_DT.color_id = dr[artifacts_DT.Enum_artifacts_DT.color_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.color_id.ToString()]);
		obj_artifacts_DT.technique_id = dr[artifacts_DT.Enum_artifacts_DT.technique_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.technique_id.ToString()]);
		obj_artifacts_DT.material_id = dr[artifacts_DT.Enum_artifacts_DT.material_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.material_id.ToString()]);
		obj_artifacts_DT.style_id = dr[artifacts_DT.Enum_artifacts_DT.style_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.style_id.ToString()]);
		obj_artifacts_DT.form_lock = dr[artifacts_DT.Enum_artifacts_DT.form_lock.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.form_lock.ToString()]);
		obj_artifacts_DT.form_status_en = dr[artifacts_DT.Enum_artifacts_DT.form_status_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.form_status_en.ToString()]);
		obj_artifacts_DT.form_lock_en = dr[artifacts_DT.Enum_artifacts_DT.form_lock_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.form_lock_en.ToString()]);
		obj_artifacts_DT.form_status_fr = dr[artifacts_DT.Enum_artifacts_DT.form_status_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.form_status_fr.ToString()]);
		obj_artifacts_DT.form_lock_fr = dr[artifacts_DT.Enum_artifacts_DT.form_lock_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.form_lock_fr.ToString()]);
		obj_artifacts_DT.form_status = dr[artifacts_DT.Enum_artifacts_DT.form_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.form_status.ToString()]);
		obj_artifacts_DT.file_status = dr[artifacts_DT.Enum_artifacts_DT.file_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.file_status.ToString()]);
        obj_artifacts_DT.save_no = dr[artifacts_DT.Enum_artifacts_DT.save_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.save_no.ToString()]);
		obj_artifacts_DT.period_id = dr[artifacts_DT.Enum_artifacts_DT.period_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.period_id.ToString()]);
		obj_artifacts_DT.assigned_to = dr[artifacts_DT.Enum_artifacts_DT.assigned_to.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.assigned_to.ToString()]);
		obj_artifacts_DT.lock_files = dr[artifacts_DT.Enum_artifacts_DT.lock_files.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_DT.Enum_artifacts_DT.lock_files.ToString()]);
		obj_artifacts_DT.source_notes = dr[artifacts_DT.Enum_artifacts_DT.source_notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.source_notes.ToString()]);
		obj_artifacts_DT.notes = dr[artifacts_DT.Enum_artifacts_DT.notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.notes.ToString()]);
		obj_artifacts_DT.era_notes = dr[artifacts_DT.Enum_artifacts_DT.era_notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.era_notes.ToString()]);
		obj_artifacts_DT.length = dr[artifacts_DT.Enum_artifacts_DT.length.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.length.ToString()]);
		obj_artifacts_DT.width = dr[artifacts_DT.Enum_artifacts_DT.width.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.width.ToString()]);
		obj_artifacts_DT.height = dr[artifacts_DT.Enum_artifacts_DT.height.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.height.ToString()]);
		obj_artifacts_DT.diameter = dr[artifacts_DT.Enum_artifacts_DT.diameter.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.diameter.ToString()]);
		obj_artifacts_DT.weight = dr[artifacts_DT.Enum_artifacts_DT.weight.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.weight.ToString()]);
		obj_artifacts_DT.perimeter = dr[artifacts_DT.Enum_artifacts_DT.perimeter.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.perimeter.ToString()]);
		obj_artifacts_DT.form_file_en = dr[artifacts_DT.Enum_artifacts_DT.form_file_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.form_file_en.ToString()]);
		obj_artifacts_DT.form_file_fr = dr[artifacts_DT.Enum_artifacts_DT.form_file_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.form_file_fr.ToString()]);
		obj_artifacts_DT.form_file = dr[artifacts_DT.Enum_artifacts_DT.form_file.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.form_file.ToString()]);
		obj_artifacts_DT.source_name = dr[artifacts_DT.Enum_artifacts_DT.source_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.source_name.ToString()]);
		obj_artifacts_DT.country = dr[artifacts_DT.Enum_artifacts_DT.country.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.country.ToString()]);
		obj_artifacts_DT.city = dr[artifacts_DT.Enum_artifacts_DT.city.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.city.ToString()]);
		obj_artifacts_DT.small_image = dr[artifacts_DT.Enum_artifacts_DT.small_image.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.small_image.ToString()]);
		obj_artifacts_DT.large_image = dr[artifacts_DT.Enum_artifacts_DT.large_image.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.large_image.ToString()]);
        obj_artifacts_DT.period_id_multi = dr[artifacts_DT.Enum_artifacts_DT.period_id_multi.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_DT.Enum_artifacts_DT.period_id_multi.ToString()]);
           return obj_artifacts_DT;
        }

        private static SqlParameter[] GetParameters(artifacts_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[37];
           
			

        parms[0] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.highlight.ToString(), obj.highlight);

        parms[1] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.highlight_panorama.ToString(), obj.highlight_panorama);
        

        parms[2] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.id.ToString(), obj.id);
        parms[2].Direction = ParameterDirection.InputOutput;

        parms[3] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.type_id.ToString(), obj.type_id);

        parms[4] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.color_id.ToString(), obj.color_id);

        parms[5] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.technique_id.ToString(), obj.technique_id);

        parms[6] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.material_id.ToString(), obj.material_id);

        parms[7] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.style_id.ToString(), obj.style_id);

        parms[8] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_lock.ToString(), obj.form_lock);

        parms[9] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_status_en.ToString(), obj.form_status_en);

        parms[10] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_lock_en.ToString(), obj.form_lock_en);

        parms[11] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_status_fr.ToString(), obj.form_status_fr);

        parms[12] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_lock_fr.ToString(), obj.form_lock_fr);

        parms[13] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_status.ToString(), obj.form_status);

        parms[14] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.file_status.ToString(), obj.file_status);

        parms[15] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.save_no.ToString(), obj.save_no);

        parms[16] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.period_id.ToString(), obj.period_id);

        parms[17] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.assigned_to.ToString(), obj.assigned_to);

        parms[18] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.lock_files.ToString(), obj.lock_files);

        parms[19] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.source_notes.ToString(), obj.source_notes);

        parms[20] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.notes.ToString(), obj.notes);

        parms[21] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.era_notes.ToString(), obj.era_notes);

        parms[22] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.length.ToString(), obj.length);

        parms[23] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.width.ToString(), obj.width);

        parms[24] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.height.ToString(), obj.height);

        parms[25] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.diameter.ToString(), obj.diameter);

        parms[26] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.weight.ToString(), obj.weight);

        parms[27] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.perimeter.ToString(), obj.perimeter);

        parms[28] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_file_en.ToString(), obj.form_file_en);

        parms[29] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_file_fr.ToString(), obj.form_file_fr);

        parms[30] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.form_file.ToString(), obj.form_file);

        parms[31] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.source_name.ToString(), obj.source_name);

        parms[32] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.country.ToString(), obj.country);

        parms[33] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.city.ToString(), obj.city);

        parms[34] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.small_image.ToString(), obj.small_image);

        parms[35] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.large_image.ToString(), obj.large_image);
        parms[36] = new SqlParameter(artifacts_DT.Enum_artifacts_DT.period_id_multi.ToString(), obj.period_id_multi);
          
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(artifacts_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "artifacts_Save", parms);

             	    obj.id = Convert.ToInt32(parms[2].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int artifacts_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "artifacts_Delete", artifacts_ID);
                return artifacts_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "artifacts_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static artifacts_DT SelectByID(int artifacts_ID)
        {
            try
            {
              if (artifacts_ID > 0)
                {
                SqlDataReader drTableName;
                artifacts_DT oInfo_artifacts_DT = new artifacts_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "artifacts_Select", artifacts_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_artifacts_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_artifacts_DT;
               }
                else
                    return new artifacts_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

