//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		artifacts_tags_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class artifacts_tags_DB
    {

        #region "Private methods"

        private static artifacts_tags_DT FillInfoObject(SqlDataReader dr)
        {

           artifacts_tags_DT obj_artifacts_tags_DT = new artifacts_tags_DT();

           
		obj_artifacts_tags_DT.id = Convert.ToInt32(dr[artifacts_tags_DT.Enum_artifacts_tags_DT.id.ToString()]);
		obj_artifacts_tags_DT.artifact_id = dr[artifacts_tags_DT.Enum_artifacts_tags_DT.artifact_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_tags_DT.Enum_artifacts_tags_DT.artifact_id.ToString()]);
		obj_artifacts_tags_DT.tag_id = dr[artifacts_tags_DT.Enum_artifacts_tags_DT.tag_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_tags_DT.Enum_artifacts_tags_DT.tag_id.ToString()]);

           return obj_artifacts_tags_DT;
        }

        private static SqlParameter[] GetParameters(artifacts_tags_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(artifacts_tags_DT.Enum_artifacts_tags_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(artifacts_tags_DT.Enum_artifacts_tags_DT.artifact_id.ToString(), obj.artifact_id);

        parms[2] = new SqlParameter(artifacts_tags_DT.Enum_artifacts_tags_DT.tag_id.ToString(), obj.tag_id);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(artifacts_tags_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "artifacts_tags_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int artifacts_tags_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "artifacts_tags_Delete", artifacts_tags_ID);
                return artifacts_tags_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "artifacts_tags_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static artifacts_tags_DT SelectByID(int artifacts_tags_ID)
        {
            try
            {
                SqlDataReader drTableName;
                artifacts_tags_DT oInfo_artifacts_tags_DT = new artifacts_tags_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "artifacts_tags_Select", artifacts_tags_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_artifacts_tags_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_artifacts_tags_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

