//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		artifacts_details_DB
// Date Generated:	14-06-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class artifacts_details_DB
    {

        #region "Private methods"

        private static artifacts_details_DT FillInfoObject(SqlDataReader dr)
        {

           artifacts_details_DT obj_artifacts_details_DT = new artifacts_details_DT();

           
		obj_artifacts_details_DT.location = dr[artifacts_details_DT.Enum_artifacts_details_DT.location.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.location.ToString()]);
		obj_artifacts_details_DT.id = Convert.ToInt32(dr[artifacts_details_DT.Enum_artifacts_details_DT.id.ToString()]);
		obj_artifacts_details_DT.artifact_id = dr[artifacts_details_DT.Enum_artifacts_details_DT.artifact_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_details_DT.Enum_artifacts_details_DT.artifact_id.ToString()]);
		obj_artifacts_details_DT.lang_id = dr[artifacts_details_DT.Enum_artifacts_details_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_details_DT.Enum_artifacts_details_DT.lang_id.ToString()]);
		obj_artifacts_details_DT.related_char_type = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_char_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_char_type.ToString()]);
		obj_artifacts_details_DT.form_pic_state = dr[artifacts_details_DT.Enum_artifacts_details_DT.form_pic_state.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_details_DT.Enum_artifacts_details_DT.form_pic_state.ToString()]);
		obj_artifacts_details_DT.content_type = dr[artifacts_details_DT.Enum_artifacts_details_DT.content_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[artifacts_details_DT.Enum_artifacts_details_DT.content_type.ToString()]);
		obj_artifacts_details_DT.artifact_brief = dr[artifacts_details_DT.Enum_artifacts_details_DT.artifact_brief.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.artifact_brief.ToString()]);
		obj_artifacts_details_DT.artifact_details = dr[artifacts_details_DT.Enum_artifacts_details_DT.artifact_details.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.artifact_details.ToString()]);
		obj_artifacts_details_DT.notes = dr[artifacts_details_DT.Enum_artifacts_details_DT.notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.notes.ToString()]);
		obj_artifacts_details_DT.period_notes = dr[artifacts_details_DT.Enum_artifacts_details_DT.period_notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.period_notes.ToString()]);
		obj_artifacts_details_DT.title = dr[artifacts_details_DT.Enum_artifacts_details_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.title.ToString()]);
		obj_artifacts_details_DT.maker_name = dr[artifacts_details_DT.Enum_artifacts_details_DT.maker_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.maker_name.ToString()]);
		obj_artifacts_details_DT.location_code = dr[artifacts_details_DT.Enum_artifacts_details_DT.location_code.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.location_code.ToString()]);
		obj_artifacts_details_DT.data_collector_name = dr[artifacts_details_DT.Enum_artifacts_details_DT.data_collector_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.data_collector_name.ToString()]);
		obj_artifacts_details_DT.data_revision_name = dr[artifacts_details_DT.Enum_artifacts_details_DT.data_revision_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.data_revision_name.ToString()]);
		obj_artifacts_details_DT.data_entry_name = dr[artifacts_details_DT.Enum_artifacts_details_DT.data_entry_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.data_entry_name.ToString()]);
		obj_artifacts_details_DT.save_org = dr[artifacts_details_DT.Enum_artifacts_details_DT.save_org.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.save_org.ToString()]);
		obj_artifacts_details_DT.save_org_no = dr[artifacts_details_DT.Enum_artifacts_details_DT.save_org_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.save_org_no.ToString()]);
		obj_artifacts_details_DT.related_event_type = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_event_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_event_type.ToString()]);
		obj_artifacts_details_DT.related_objectives = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_objectives.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_objectives.ToString()]);
		obj_artifacts_details_DT.related_obj_type = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_obj_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_obj_type.ToString()]);
		obj_artifacts_details_DT.related_art_date = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_art_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_art_date.ToString()]);
		obj_artifacts_details_DT.start_date = dr[artifacts_details_DT.Enum_artifacts_details_DT.start_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.start_date.ToString()]);
		obj_artifacts_details_DT.end_date = dr[artifacts_details_DT.Enum_artifacts_details_DT.end_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.end_date.ToString()]);
		obj_artifacts_details_DT.data_entry_revision_name = dr[artifacts_details_DT.Enum_artifacts_details_DT.data_entry_revision_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.data_entry_revision_name.ToString()]);
		obj_artifacts_details_DT.make_date = dr[artifacts_details_DT.Enum_artifacts_details_DT.make_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.make_date.ToString()]);
		obj_artifacts_details_DT.keywords = dr[artifacts_details_DT.Enum_artifacts_details_DT.keywords.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.keywords.ToString()]);
		obj_artifacts_details_DT.related_char_names = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_char_names.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_char_names.ToString()]);
		obj_artifacts_details_DT.related_loc_type = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_loc_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_loc_type.ToString()]);
		obj_artifacts_details_DT.related_event = dr[artifacts_details_DT.Enum_artifacts_details_DT.related_event.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[artifacts_details_DT.Enum_artifacts_details_DT.related_event.ToString()]);

           return obj_artifacts_details_DT;
        }

        private static SqlParameter[] GetParameters(artifacts_details_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[31];
           
			

        parms[0] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.location.ToString(), obj.location);
        

        parms[1] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.id.ToString(), obj.id);
        parms[1].Direction = ParameterDirection.InputOutput;

        parms[2] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.artifact_id.ToString(), obj.artifact_id);

        parms[3] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.lang_id.ToString(), obj.lang_id);

        parms[4] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_char_type.ToString(), obj.related_char_type);

        parms[5] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.form_pic_state.ToString(), obj.form_pic_state);

        parms[6] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.content_type.ToString(), obj.content_type);

        parms[7] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.artifact_brief.ToString(), obj.artifact_brief);

        parms[8] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.artifact_details.ToString(), obj.artifact_details);

        parms[9] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.notes.ToString(), obj.notes);

        parms[10] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.period_notes.ToString(), obj.period_notes);

        parms[11] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.title.ToString(), obj.title);

        parms[12] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.maker_name.ToString(), obj.maker_name);

        parms[13] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.location_code.ToString(), obj.location_code);

        parms[14] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.data_collector_name.ToString(), obj.data_collector_name);

        parms[15] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.data_revision_name.ToString(), obj.data_revision_name);

        parms[16] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.data_entry_name.ToString(), obj.data_entry_name);

        parms[17] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.save_org.ToString(), obj.save_org);

        parms[18] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.save_org_no.ToString(), obj.save_org_no);

        parms[19] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_event_type.ToString(), obj.related_event_type);

        parms[20] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_objectives.ToString(), obj.related_objectives);

        parms[21] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_obj_type.ToString(), obj.related_obj_type);

        parms[22] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_art_date.ToString(), obj.related_art_date);

        parms[23] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.start_date.ToString(), obj.start_date);

        parms[24] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.end_date.ToString(), obj.end_date);

        parms[25] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.data_entry_revision_name.ToString(), obj.data_entry_revision_name);

        parms[26] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.make_date.ToString(), obj.make_date);

        parms[27] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.keywords.ToString(), obj.keywords);

        parms[28] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_char_names.ToString(), obj.related_char_names);

        parms[29] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_loc_type.ToString(), obj.related_loc_type);

        parms[30] = new SqlParameter(artifacts_details_DT.Enum_artifacts_details_DT.related_event.ToString(), obj.related_event);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(artifacts_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "artifacts_details_Save", parms);

             	    obj.id = Convert.ToInt32(parms[1].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int artifacts_details_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "artifacts_details_Delete", artifacts_details_ID);
                return artifacts_details_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "artifacts_details_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static artifacts_details_DT SelectByID(int artifacts_details_ID)
        {
            try
            {
              if (artifacts_details_ID > 0)
                {
                SqlDataReader drTableName;
                artifacts_details_DT oInfo_artifacts_details_DT = new artifacts_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "artifacts_details_select2", artifacts_details_ID,menus_update.get_current_lang());
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_artifacts_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_artifacts_details_DT;
               }
                else
                    return new artifacts_details_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

