//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		authors_details_DB
// Date Generated:	30-12-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class authors_details_DB
    {

        #region "Private methods"

        private static authors_details_DT FillInfoObject(SqlDataReader dr)
        {

           authors_details_DT obj_authors_details_DT = new authors_details_DT();

           
		obj_authors_details_DT.details = dr[authors_details_DT.Enum_authors_details_DT.details.ToString()] == DBNull.Value ? null : Convert.ToString(dr[authors_details_DT.Enum_authors_details_DT.details.ToString()]);
		obj_authors_details_DT.id = Convert.ToInt32(dr[authors_details_DT.Enum_authors_details_DT.id.ToString()]);
		obj_authors_details_DT.author_id = dr[authors_details_DT.Enum_authors_details_DT.author_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[authors_details_DT.Enum_authors_details_DT.author_id.ToString()]);
		obj_authors_details_DT.lang_id = dr[authors_details_DT.Enum_authors_details_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[authors_details_DT.Enum_authors_details_DT.lang_id.ToString()]);
		obj_authors_details_DT.name = dr[authors_details_DT.Enum_authors_details_DT.name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[authors_details_DT.Enum_authors_details_DT.name.ToString()]);
		obj_authors_details_DT.address = dr[authors_details_DT.Enum_authors_details_DT.address.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[authors_details_DT.Enum_authors_details_DT.address.ToString()]);
		obj_authors_details_DT.title = dr[authors_details_DT.Enum_authors_details_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[authors_details_DT.Enum_authors_details_DT.title.ToString()]);
		obj_authors_details_DT.name_fromtitle = dr[authors_details_DT.Enum_authors_details_DT.name_fromtitle.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[authors_details_DT.Enum_authors_details_DT.name_fromtitle.ToString()]);
		obj_authors_details_DT.name_fromheader = dr[authors_details_DT.Enum_authors_details_DT.name_fromheader.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[authors_details_DT.Enum_authors_details_DT.name_fromheader.ToString()]);

           return obj_authors_details_DT;
        }

        private static SqlParameter[] GetParameters(authors_details_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[9];
           
			

        parms[0] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.details.ToString(), obj.details);
        

        parms[1] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.id.ToString(), obj.id);
        parms[1].Direction = ParameterDirection.InputOutput;

        parms[2] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.author_id.ToString(), obj.author_id);

        parms[3] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.lang_id.ToString(), obj.lang_id);

        parms[4] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.name.ToString(), obj.name);

        parms[5] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.address.ToString(), obj.address);

        parms[6] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.title.ToString(), obj.title);

        parms[7] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.name_fromtitle.ToString(), obj.name_fromtitle);

        parms[8] = new SqlParameter(authors_details_DT.Enum_authors_details_DT.name_fromheader.ToString(), obj.name_fromheader);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(authors_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "authors_details_Save", parms);

             	    obj.id = Convert.ToInt32(parms[1].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int authors_details_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "authors_details_Delete", authors_details_ID);
                return authors_details_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "authors_details_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static authors_details_DT SelectByID(int authors_details_ID)
        {
            try
            {
              if (authors_details_ID > 0)
                {
                SqlDataReader drTableName;
                authors_details_DT oInfo_authors_details_DT = new authors_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "authors_details_Select", authors_details_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_authors_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_authors_details_DT;
               }
                else
                    return new authors_details_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

