//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		awsema_DB
// Date Generated:	05-08-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class awsema_DB
    {

        #region "Private methods"

        private static awsema_DT FillInfoObject(SqlDataReader dr)
        {

           awsema_DT obj_awsema_DT = new awsema_DT();

           
		obj_awsema_DT.id = Convert.ToInt32(dr[awsema_DT.Enum_awsema_DT.id.ToString()]);
		obj_awsema_DT.char_id = dr[awsema_DT.Enum_awsema_DT.char_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[awsema_DT.Enum_awsema_DT.char_id.ToString()]);
		obj_awsema_DT.type = dr[awsema_DT.Enum_awsema_DT.type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[awsema_DT.Enum_awsema_DT.type.ToString()]);

           return obj_awsema_DT;
        }

        private static SqlParameter[] GetParameters(awsema_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(awsema_DT.Enum_awsema_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(awsema_DT.Enum_awsema_DT.char_id.ToString(), obj.char_id);

        parms[2] = new SqlParameter(awsema_DT.Enum_awsema_DT.type.ToString(), obj.type);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(awsema_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "awsema_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int awsema_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "awsema_Delete", awsema_ID);
                return awsema_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "awsema_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static awsema_DT SelectByID(int awsema_ID)
        {
            try
            {
              if (awsema_ID > 0)
                {
                SqlDataReader drTableName;
                awsema_DT oInfo_awsema_DT = new awsema_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "awsema_Select", awsema_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_awsema_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_awsema_DT;
               }
                else
                    return new awsema_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

