//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		char_moalafat_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


public static class char_moalafat_DB
{

    #region "Private methods"

    private static char_moalafat_DT FillInfoObject(SqlDataReader dr)
    {

        char_moalafat_DT obj_char_moalafat_DT = new char_moalafat_DT();


        obj_char_moalafat_DT.id = Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.id.ToString()]);
        obj_char_moalafat_DT.char_id = dr[char_moalafat_DT.Enum_char_moalafat_DT.char_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.char_id.ToString()]);
        obj_char_moalafat_DT.moalaf_type = dr[char_moalafat_DT.Enum_char_moalafat_DT.moalaf_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.moalaf_type.ToString()]);
        obj_char_moalafat_DT.title_ar = dr[char_moalafat_DT.Enum_char_moalafat_DT.title_ar.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[char_moalafat_DT.Enum_char_moalafat_DT.title_ar.ToString()]);
        obj_char_moalafat_DT.title_en = dr[char_moalafat_DT.Enum_char_moalafat_DT.title_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[char_moalafat_DT.Enum_char_moalafat_DT.title_en.ToString()]);
        obj_char_moalafat_DT.title_fr = dr[char_moalafat_DT.Enum_char_moalafat_DT.title_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[char_moalafat_DT.Enum_char_moalafat_DT.title_fr.ToString()]);
        obj_char_moalafat_DT.field_name = dr[char_moalafat_DT.Enum_char_moalafat_DT.field_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[char_moalafat_DT.Enum_char_moalafat_DT.field_name.ToString()]);
        obj_char_moalafat_DT.content_id = dr[char_moalafat_DT.Enum_char_moalafat_DT.content_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.content_id.ToString()]);
        obj_char_moalafat_DT.content_type = dr[char_moalafat_DT.Enum_char_moalafat_DT.content_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.content_type.ToString()]);
        obj_char_moalafat_DT.complete = dr[char_moalafat_DT.Enum_char_moalafat_DT.complete.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.complete.ToString()]);
        obj_char_moalafat_DT.candidate = dr[char_moalafat_DT.Enum_char_moalafat_DT.candidate.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[char_moalafat_DT.Enum_char_moalafat_DT.candidate.ToString()]);


        return obj_char_moalafat_DT;
    }

    private static SqlParameter[] GetParameters(char_moalafat_DT obj)
    {
        SqlParameter[] parms = new SqlParameter[11];


        parms[0] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.char_id.ToString(), obj.char_id);

        parms[2] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.moalaf_type.ToString(), obj.moalaf_type);

        parms[3] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.title_ar.ToString(), obj.title_ar);

        parms[4] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.title_en.ToString(), obj.title_en);

        parms[5] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.title_fr.ToString(), obj.title_fr);

        parms[6] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.field_name.ToString(), obj.field_name);

        parms[7] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.content_id.ToString(), obj.content_id);
        parms[8] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.content_type.ToString(), obj.content_type);
        parms[9] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.complete.ToString(), obj.complete);
        parms[10] = new SqlParameter(char_moalafat_DT.Enum_char_moalafat_DT.candidate.ToString(), obj.candidate);


        return parms;
    }

    #endregion

    #region "DB methods"

    public static int Save(char_moalafat_DT obj)
    {
        try
        {
            SqlParameter[] parms = GetParameters(obj);

            SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "char_moalafat_Save", parms);
            return Convert.ToInt32(parms[0].Value);
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static int Delete(int char_moalafat_ID)
    {
        try
        {
            SqlHelper.ExecuteNonQuery(Database.ConnectionString, "char_moalafat_Delete", char_moalafat_ID);
            return char_moalafat_ID;
        }
        catch (Exception ex)
        {

            return -1;
        }
    }

    public static DataTable SelectAll()
    {
        try
        {
            return SqlHelper.ExecuteDataset(Database.ConnectionString, "char_moalafat_Select", 0).Tables[0];

        }
        catch (Exception ex)
        {

            return null;
        }
    }

    public static DataTable SelectByContent_id(int char_id)
    {
        try
        {
            return SqlHelper.ExecuteDataset(Database.ConnectionString, "char_moalafat_char_id", char_id).Tables[0];

        }
        catch (Exception ex)
        {

            return null;
        }


    }
    public static char_moalafat_DT SelectByID(int char_moalafat_ID)
    {
        try
        {
            SqlDataReader drTableName;
            char_moalafat_DT oInfo_char_moalafat_DT = new char_moalafat_DT();

            drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "char_moalafat_Select", char_moalafat_ID);
            if (drTableName != null)
            {
                while (drTableName.Read())
                {
                    oInfo_char_moalafat_DT = FillInfoObject(drTableName);
                }

                drTableName.Close();
            }
            return oInfo_char_moalafat_DT;
        }
        catch (Exception ex)
        {

            return null;
        }
    }
    #endregion


}

