//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	NOURASULTAN\Eng Ahmed Soltaen using Mcit Generator
// Class Name:		characters_details_DB
// Date Generated:	31-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class characters_details_DB
    {

        #region "Private methods"

        private static characters_details_DT FillInfoObject(SqlDataReader dr)
        {
        characters_details_DT obj_characters_details_DT = new characters_details_DT();

        obj_characters_details_DT.id = Convert.ToInt32(dr[characters_details_DT.Enum_characters_details_DT.id.ToString()]);
    
		obj_characters_details_DT.titles = dr[characters_details_DT.Enum_characters_details_DT.titles.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.titles.ToString()]);
		obj_characters_details_DT.other_names = dr[characters_details_DT.Enum_characters_details_DT.other_names.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.other_names.ToString()]);
		obj_characters_details_DT.char_id = dr[characters_details_DT.Enum_characters_details_DT.char_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[characters_details_DT.Enum_characters_details_DT.char_id.ToString()]);
		obj_characters_details_DT.lang_id = dr[characters_details_DT.Enum_characters_details_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[characters_details_DT.Enum_characters_details_DT.lang_id.ToString()]);
		obj_characters_details_DT.form_pic_state = dr[characters_details_DT.Enum_characters_details_DT.form_pic_state.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[characters_details_DT.Enum_characters_details_DT.form_pic_state.ToString()]);
		obj_characters_details_DT.char_brief = dr[characters_details_DT.Enum_characters_details_DT.char_brief.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.char_brief.ToString()]);
		obj_characters_details_DT.char_details = dr[characters_details_DT.Enum_characters_details_DT.char_details.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.char_details.ToString()]);
		obj_characters_details_DT.scientific_life = dr[characters_details_DT.Enum_characters_details_DT.scientific_life.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.scientific_life.ToString()]);
		obj_characters_details_DT.mashyakha_azhar = dr[characters_details_DT.Enum_characters_details_DT.mashyakha_azhar.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.mashyakha_azhar.ToString()]);
		obj_characters_details_DT.birth_details = dr[characters_details_DT.Enum_characters_details_DT.birth_details.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.birth_details.ToString()]);
		obj_characters_details_DT.working_life = dr[characters_details_DT.Enum_characters_details_DT.working_life.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.working_life.ToString()]);
		obj_characters_details_DT.activities = dr[characters_details_DT.Enum_characters_details_DT.activities.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.activities.ToString()]);
		obj_characters_details_DT.keywords = dr[characters_details_DT.Enum_characters_details_DT.keywords.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.keywords.ToString()]);
		obj_characters_details_DT.notes = dr[characters_details_DT.Enum_characters_details_DT.notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.notes.ToString()]);
		obj_characters_details_DT.written_about = dr[characters_details_DT.Enum_characters_details_DT.written_about.ToString()] == DBNull.Value ? null : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.written_about.ToString()]);
		obj_characters_details_DT.name = dr[characters_details_DT.Enum_characters_details_DT.name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.name.ToString()]);
		obj_characters_details_DT.birth_date = dr[characters_details_DT.Enum_characters_details_DT.birth_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.birth_date.ToString()]);
		obj_characters_details_DT.death_date = dr[characters_details_DT.Enum_characters_details_DT.death_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.death_date.ToString()]);
		obj_characters_details_DT.hbirth_date = dr[characters_details_DT.Enum_characters_details_DT.hbirth_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.hbirth_date.ToString()]);
		obj_characters_details_DT.hdeath_date = dr[characters_details_DT.Enum_characters_details_DT.hdeath_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.hdeath_date.ToString()]);
		obj_characters_details_DT.data_collector_name = dr[characters_details_DT.Enum_characters_details_DT.data_collector_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.data_collector_name.ToString()]);
		obj_characters_details_DT.data_revision_name = dr[characters_details_DT.Enum_characters_details_DT.data_revision_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.data_revision_name.ToString()]);
		obj_characters_details_DT.data_entry_name = dr[characters_details_DT.Enum_characters_details_DT.data_entry_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.data_entry_name.ToString()]);
		obj_characters_details_DT.data_entry_revision_name = dr[characters_details_DT.Enum_characters_details_DT.data_entry_revision_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[characters_details_DT.Enum_characters_details_DT.data_entry_revision_name.ToString()]);
          
            return obj_characters_details_DT;
        }

        private static SqlParameter[] GetParameters(characters_details_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[25];


            parms[0] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.id.ToString(), obj.id);
            parms[0].Direction = ParameterDirection.InputOutput;


            parms[1] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.titles.ToString(), obj.titles);

            parms[2] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.other_names.ToString(), obj.other_names);


           

            parms[3] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.char_id.ToString(), obj.char_id);

            parms[4] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.lang_id.ToString(), obj.lang_id);

            parms[5] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.form_pic_state.ToString(), obj.form_pic_state);

            parms[6] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.char_brief.ToString(), obj.char_brief);

            parms[7] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.char_details.ToString(), obj.char_details);

            parms[8] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.scientific_life.ToString(), obj.scientific_life);

            parms[9] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.mashyakha_azhar.ToString(), obj.mashyakha_azhar);

            parms[10] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.birth_details.ToString(), obj.birth_details);

            parms[11] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.working_life.ToString(), obj.working_life);

            parms[12] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.activities.ToString(), obj.activities);

            parms[13] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.keywords.ToString(), obj.keywords);

            parms[14] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.notes.ToString(), obj.notes);

            parms[15] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.written_about.ToString(), obj.written_about);

            parms[16] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.name.ToString(), obj.name);

            parms[17] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.birth_date.ToString(), obj.birth_date);

            parms[18] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.death_date.ToString(), obj.death_date);

            parms[19] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.hbirth_date.ToString(), obj.hbirth_date);

            parms[20] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.hdeath_date.ToString(), obj.hdeath_date);

            parms[21] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.data_collector_name.ToString(), obj.data_collector_name);

            parms[22] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.data_revision_name.ToString(), obj.data_revision_name);

            parms[23] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.data_entry_name.ToString(), obj.data_entry_name);

            parms[24] = new SqlParameter(characters_details_DT.Enum_characters_details_DT.data_entry_revision_name.ToString(), obj.data_entry_revision_name);

            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(characters_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "characters_details_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }
        public static int Update(characters_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "characters_details_Save_Update", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

       

        public static int Delete(int characters_details_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "characters_details_Delete", characters_details_ID);
                return characters_details_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "characters_details_Select", 0,menus_update.get_current_lang()).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
        }
        public static DataTable SelectBylang_ID(int lang_id)
        {
           
        
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "characters_details_Select",0,lang_id).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        
        }

        public static characters_details_DT SelectByID(int characters_details_ID)
        {
            try
            {
                SqlDataReader drTableName;
                characters_details_DT oInfo_characters_details_DT = new characters_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "characters_details_Select", characters_details_ID,menus_update.get_current_lang());
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_characters_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_characters_details_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static characters_details_DT SelectBychar_ID(int characters_details_ID , int lang_id)
        {
            try
            {
                SqlDataReader drTableName;
                characters_details_DT oInfo_characters_details_DT = new characters_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "characters_details_select_bychar_id", characters_details_ID, lang_id);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_characters_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_characters_details_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }

	#endregion


    }

