//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		content_files_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class content_files_DB
    {

        #region "Private methods"

        private static content_files_DT FillInfoObject(SqlDataReader dr)
        {

           content_files_DT obj_content_files_DT = new content_files_DT();

           
		obj_content_files_DT.id = Convert.ToInt32(dr[content_files_DT.Enum_content_files_DT.id.ToString()]);
		obj_content_files_DT.content_type = dr[content_files_DT.Enum_content_files_DT.content_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_files_DT.Enum_content_files_DT.content_type.ToString()]);
		obj_content_files_DT.field_name = dr[content_files_DT.Enum_content_files_DT.field_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_files_DT.Enum_content_files_DT.field_name.ToString()]);
		obj_content_files_DT.usage = dr[content_files_DT.Enum_content_files_DT.usage.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_files_DT.Enum_content_files_DT.usage.ToString()]);
		obj_content_files_DT.valid_extension = dr[content_files_DT.Enum_content_files_DT.valid_extension.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_files_DT.Enum_content_files_DT.valid_extension.ToString()]);

           return obj_content_files_DT;
        }

        private static SqlParameter[] GetParameters(content_files_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[5];
           
			
        

        parms[0] = new SqlParameter(content_files_DT.Enum_content_files_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(content_files_DT.Enum_content_files_DT.content_type.ToString(), obj.content_type);

        parms[2] = new SqlParameter(content_files_DT.Enum_content_files_DT.field_name.ToString(), obj.field_name);

        parms[3] = new SqlParameter(content_files_DT.Enum_content_files_DT.usage.ToString(), obj.usage);

        parms[4] = new SqlParameter(content_files_DT.Enum_content_files_DT.valid_extension.ToString(), obj.valid_extension);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(content_files_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "content_files_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int content_files_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "content_files_Delete", content_files_ID);
                return content_files_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "content_files_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static content_files_DT SelectByID(int content_files_ID)
        {
            try
            {
                SqlDataReader drTableName;
                content_files_DT oInfo_content_files_DT = new content_files_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "content_files_Select", content_files_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_content_files_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_content_files_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

