//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		contents_timeline_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class contents_timeline_DB
    {

        #region "Private methods"

        private static contents_timeline_DT FillInfoObject(SqlDataReader dr)
        {

            contents_timeline_DT obj_contents_timeline_DT = new contents_timeline_DT();


            obj_contents_timeline_DT.date_type = dr[contents_timeline_DT.Enum_contents_timeline_DT.date_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[contents_timeline_DT.Enum_contents_timeline_DT.date_type.ToString()]);
            obj_contents_timeline_DT.id = Convert.ToInt32(dr[contents_timeline_DT.Enum_contents_timeline_DT.id.ToString()]);
            obj_contents_timeline_DT.content_id = dr[contents_timeline_DT.Enum_contents_timeline_DT.content_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[contents_timeline_DT.Enum_contents_timeline_DT.content_id.ToString()]);
            obj_contents_timeline_DT.century_id = dr[contents_timeline_DT.Enum_contents_timeline_DT.century_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[contents_timeline_DT.Enum_contents_timeline_DT.century_id.ToString()]);
            obj_contents_timeline_DT.period_id = dr[contents_timeline_DT.Enum_contents_timeline_DT.period_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[contents_timeline_DT.Enum_contents_timeline_DT.period_id.ToString()]);
            obj_contents_timeline_DT.lang_id = dr[contents_timeline_DT.Enum_contents_timeline_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[contents_timeline_DT.Enum_contents_timeline_DT.lang_id.ToString()]);
            obj_contents_timeline_DT.melady_date_from = dr[contents_timeline_DT.Enum_contents_timeline_DT.melady_date_from.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.melady_date_from.ToString()]);
            obj_contents_timeline_DT.melady_date_to = dr[contents_timeline_DT.Enum_contents_timeline_DT.melady_date_to.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.melady_date_to.ToString()]);
            obj_contents_timeline_DT.hegry_date_from = dr[contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_from.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_from.ToString()]);
            obj_contents_timeline_DT.hegry_date_to = dr[contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_to.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_to.ToString()]);
            obj_contents_timeline_DT.content_type = dr[contents_timeline_DT.Enum_contents_timeline_DT.content_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.content_type.ToString()]);
            obj_contents_timeline_DT.notes = dr[contents_timeline_DT.Enum_contents_timeline_DT.notes.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.notes.ToString()]);
            obj_contents_timeline_DT.melady_date_rep = dr[contents_timeline_DT.Enum_contents_timeline_DT.melady_date_rep.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.melady_date_rep.ToString()]);
            obj_contents_timeline_DT.hegry_date_rep = dr[contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_rep.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_rep.ToString()]);
            obj_contents_timeline_DT.reason_note = dr[contents_timeline_DT.Enum_contents_timeline_DT.reason_note.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_timeline_DT.Enum_contents_timeline_DT.reason_note.ToString()]);
            return obj_contents_timeline_DT;
        }

        private static SqlParameter[] GetParameters(contents_timeline_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[15];



            parms[0] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.date_type.ToString(), obj.date_type);


            parms[1] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.id.ToString(), obj.id);
            parms[1].Direction = ParameterDirection.InputOutput;

            parms[2] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.content_id.ToString(), obj.content_id);

            parms[3] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.century_id.ToString(), obj.century_id);

            parms[4] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.period_id.ToString(), obj.period_id);

            parms[5] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.lang_id.ToString(), obj.lang_id);

            parms[6] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.melady_date_from.ToString(), obj.melady_date_from);

            parms[7] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.melady_date_to.ToString(), obj.melady_date_to);

            parms[8] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_from.ToString(), obj.hegry_date_from);

            parms[9] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_to.ToString(), obj.hegry_date_to);

            parms[10] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.content_type.ToString(), obj.content_type);

            parms[11] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.notes.ToString(), obj.notes);

            parms[12] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.melady_date_rep.ToString(), obj.melady_date_rep);
            parms[13] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.hegry_date_rep.ToString(), obj.hegry_date_rep);
            parms[14] = new SqlParameter(contents_timeline_DT.Enum_contents_timeline_DT.reason_note.ToString(), obj.reason_note);

            return parms;
        }

        #endregion

	#region "DB methods"
        public static int Save_content(contents_timeline_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "content_timeline_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }
        public static int Save(contents_timeline_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "contents_timeline_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int contents_timeline_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "contents_timeline_Delete", contents_timeline_ID);
                return contents_timeline_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "contents_timeline_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static contents_timeline_DT SelectByID(int contents_timeline_ID)
        {
            try
            {
                SqlDataReader drTableName;
                contents_timeline_DT oInfo_contents_timeline_DT = new contents_timeline_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "contents_timeline_Select", contents_timeline_ID,menus_update.get_current_lang ());
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_contents_timeline_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_contents_timeline_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }

	#endregion
        public static DataTable SelectByIDandType(int content_id, int content_type)
        {
            try
            {
                return SqlHelper.ExecuteDataset(Database.ConnectionString, "content_timeline_Select", content_id, content_type,menus_update.get_current_lang()).Tables[0];

            }
            catch (Exception ex)
            {

                return null;
            }
            
        }


    }

