//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		contents_operations_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class contents_operations_DB
    {

        #region "Private methods"

        private static contents_operations_DT FillInfoObject(SqlDataReader dr)
        {

           contents_operations_DT obj_contents_operations_DT = new contents_operations_DT();

           
		obj_contents_operations_DT.id = Convert.ToInt32(dr[contents_operations_DT.Enum_contents_operations_DT.id.ToString()]);
		obj_contents_operations_DT.operation = dr[contents_operations_DT.Enum_contents_operations_DT.operation.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[contents_operations_DT.Enum_contents_operations_DT.operation.ToString()]);

           return obj_contents_operations_DT;
        }

        private static SqlParameter[] GetParameters(contents_operations_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[2];
           
			
        

        parms[0] = new SqlParameter(contents_operations_DT.Enum_contents_operations_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(contents_operations_DT.Enum_contents_operations_DT.operation.ToString(), obj.operation);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(contents_operations_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "contents_operations_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int contents_operations_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "contents_operations_Delete", contents_operations_ID);
                return contents_operations_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "contents_operations_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static contents_operations_DT SelectByID(int contents_operations_ID)
        {
            try
            {
                SqlDataReader drTableName;
                contents_operations_DT oInfo_contents_operations_DT = new contents_operations_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "contents_operations_Select", contents_operations_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_contents_operations_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_contents_operations_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

