//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		content_files_info_DB
// Date Generated:	24-01-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class content_files_info_DB
    {

        #region "Private methods"

        private static content_files_info_DT FillInfoObject(SqlDataReader dr)
        {

           content_files_info_DT obj_content_files_info_DT = new content_files_info_DT();

           
		obj_content_files_info_DT.id = Convert.ToInt32(dr[content_files_info_DT.Enum_content_files_info_DT.id.ToString()]);
		obj_content_files_info_DT.content_id = dr[content_files_info_DT.Enum_content_files_info_DT.content_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_files_info_DT.Enum_content_files_info_DT.content_id.ToString()]);
		obj_content_files_info_DT.width = dr[content_files_info_DT.Enum_content_files_info_DT.width.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_files_info_DT.Enum_content_files_info_DT.width.ToString()]);
		obj_content_files_info_DT.height = dr[content_files_info_DT.Enum_content_files_info_DT.height.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_files_info_DT.Enum_content_files_info_DT.height.ToString()]);
		obj_content_files_info_DT.size = dr[content_files_info_DT.Enum_content_files_info_DT.size.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_files_info_DT.Enum_content_files_info_DT.size.ToString()]);
		obj_content_files_info_DT.file_ext = dr[content_files_info_DT.Enum_content_files_info_DT.file_ext.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_files_info_DT.Enum_content_files_info_DT.file_ext.ToString()]);
		obj_content_files_info_DT.file_key = dr[content_files_info_DT.Enum_content_files_info_DT.file_key.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_files_info_DT.Enum_content_files_info_DT.file_key.ToString()]);
		obj_content_files_info_DT.period = dr[content_files_info_DT.Enum_content_files_info_DT.period.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_files_info_DT.Enum_content_files_info_DT.period.ToString()]);

           return obj_content_files_info_DT;
        }

        private static SqlParameter[] GetParameters(content_files_info_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[8];
           
			
        

        parms[0] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.content_id.ToString(), obj.content_id);

        parms[2] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.width.ToString(), obj.width);

        parms[3] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.height.ToString(), obj.height);

        parms[4] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.size.ToString(), obj.size);

        parms[5] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.file_ext.ToString(), obj.file_ext);

        parms[6] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.file_key.ToString(), obj.file_key);

        parms[7] = new SqlParameter(content_files_info_DT.Enum_content_files_info_DT.period.ToString(), obj.period);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(content_files_info_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "content_files_info_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int content_files_info_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "content_files_info_Delete", content_files_info_ID);
                return content_files_info_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "content_files_info_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static content_files_info_DT SelectByID(int content_files_info_ID)
        {
            try
            {
                SqlDataReader drTableName;
                content_files_info_DT oInfo_content_files_info_DT = new content_files_info_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "content_files_info_Select", content_files_info_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_content_files_info_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_content_files_info_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

