//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		content_images_DB
// Date Generated:	08-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class content_images_DB
    {

        #region "Private methods"

        private static content_images_DT FillInfoObject(SqlDataReader dr)
        {

           content_images_DT obj_content_images_DT = new content_images_DT();

           
		obj_content_images_DT.highlight = dr[content_images_DT.Enum_content_images_DT.highlight.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.highlight.ToString()]);
		obj_content_images_DT.highlight_panorama = dr[content_images_DT.Enum_content_images_DT.highlight_panorama.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.highlight_panorama.ToString()]);
		obj_content_images_DT.id = Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.id.ToString()]);
		obj_content_images_DT.content_id = dr[content_images_DT.Enum_content_images_DT.content_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.content_id.ToString()]);
		obj_content_images_DT.content_type = dr[content_images_DT.Enum_content_images_DT.content_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.content_type.ToString()]);
		obj_content_images_DT.assigned_to = dr[content_images_DT.Enum_content_images_DT.assigned_to.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.assigned_to.ToString()]);
		obj_content_images_DT.form_pic_state = dr[content_images_DT.Enum_content_images_DT.form_pic_state.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_pic_state.ToString()]);
		obj_content_images_DT.pic_type = dr[content_images_DT.Enum_content_images_DT.pic_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.pic_type.ToString()]);
		obj_content_images_DT.form_status_en = dr[content_images_DT.Enum_content_images_DT.form_status_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_status_en.ToString()]);
		obj_content_images_DT.form_lock_en = dr[content_images_DT.Enum_content_images_DT.form_lock_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_lock_en.ToString()]);
		obj_content_images_DT.form_status_fr = dr[content_images_DT.Enum_content_images_DT.form_status_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_status_fr.ToString()]);
		obj_content_images_DT.form_lock_fr = dr[content_images_DT.Enum_content_images_DT.form_lock_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_lock_fr.ToString()]);
		obj_content_images_DT.special_element = dr[content_images_DT.Enum_content_images_DT.special_element.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.special_element.ToString()]);
		obj_content_images_DT.form_status = dr[content_images_DT.Enum_content_images_DT.form_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_status.ToString()]);
		obj_content_images_DT.file_status = dr[content_images_DT.Enum_content_images_DT.file_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.file_status.ToString()]);
		obj_content_images_DT.form_lock = dr[content_images_DT.Enum_content_images_DT.form_lock.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.form_lock.ToString()]);
		obj_content_images_DT.lock_files = dr[content_images_DT.Enum_content_images_DT.lock_files.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.lock_files.ToString()]);
		obj_content_images_DT.period_id = dr[content_images_DT.Enum_content_images_DT.period_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_images_DT.Enum_content_images_DT.period_id.ToString()]);
		obj_content_images_DT.large_image = dr[content_images_DT.Enum_content_images_DT.large_image.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.large_image.ToString()]);
		obj_content_images_DT.normal_image = dr[content_images_DT.Enum_content_images_DT.normal_image.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.normal_image.ToString()]);
		obj_content_images_DT.small_image = dr[content_images_DT.Enum_content_images_DT.small_image.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.small_image.ToString()]);
		obj_content_images_DT.size = dr[content_images_DT.Enum_content_images_DT.size.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.size.ToString()]);
		obj_content_images_DT.record_date_georgian = dr[content_images_DT.Enum_content_images_DT.record_date_georgian.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.record_date_georgian.ToString()]);
		obj_content_images_DT.record_date_hijri = dr[content_images_DT.Enum_content_images_DT.record_date_hijri.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.record_date_hijri.ToString()]);
		obj_content_images_DT.form_file = dr[content_images_DT.Enum_content_images_DT.form_file.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.form_file.ToString()]);
		obj_content_images_DT.form_file_en = dr[content_images_DT.Enum_content_images_DT.form_file_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.form_file_en.ToString()]);
		obj_content_images_DT.form_file_fr = dr[content_images_DT.Enum_content_images_DT.form_file_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.form_file_fr.ToString()]);
        obj_content_images_DT.period_id_multi = dr[content_images_DT.Enum_content_images_DT.period_id_multi.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_images_DT.Enum_content_images_DT.period_id_multi.ToString()]);
		   
           return obj_content_images_DT;
        }

        private static SqlParameter[] GetParameters(content_images_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[28];
           
			

        parms[0] = new SqlParameter(content_images_DT.Enum_content_images_DT.highlight.ToString(), obj.highlight);

        parms[1] = new SqlParameter(content_images_DT.Enum_content_images_DT.highlight_panorama.ToString(), obj.highlight_panorama);
        

        parms[2] = new SqlParameter(content_images_DT.Enum_content_images_DT.id.ToString(), obj.id);
        parms[2].Direction = ParameterDirection.InputOutput;

        parms[3] = new SqlParameter(content_images_DT.Enum_content_images_DT.content_id.ToString(), obj.content_id);

        parms[4] = new SqlParameter(content_images_DT.Enum_content_images_DT.content_type.ToString(), obj.content_type);

        parms[5] = new SqlParameter(content_images_DT.Enum_content_images_DT.assigned_to.ToString(), obj.assigned_to);

        parms[6] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_pic_state.ToString(), obj.form_pic_state);

        parms[7] = new SqlParameter(content_images_DT.Enum_content_images_DT.pic_type.ToString(), obj.pic_type);

        parms[8] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_status_en.ToString(), obj.form_status_en);

        parms[9] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_lock_en.ToString(), obj.form_lock_en);

        parms[10] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_status_fr.ToString(), obj.form_status_fr);

        parms[11] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_lock_fr.ToString(), obj.form_lock_fr);

        parms[12] = new SqlParameter(content_images_DT.Enum_content_images_DT.special_element.ToString(), obj.special_element);

        parms[13] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_status.ToString(), obj.form_status);

        parms[14] = new SqlParameter(content_images_DT.Enum_content_images_DT.file_status.ToString(), obj.file_status);

        parms[15] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_lock.ToString(), obj.form_lock);

        parms[16] = new SqlParameter(content_images_DT.Enum_content_images_DT.lock_files.ToString(), obj.lock_files);

        parms[17] = new SqlParameter(content_images_DT.Enum_content_images_DT.period_id.ToString(), obj.period_id);

        parms[18] = new SqlParameter(content_images_DT.Enum_content_images_DT.large_image.ToString(), obj.large_image);

        parms[19] = new SqlParameter(content_images_DT.Enum_content_images_DT.normal_image.ToString(), obj.normal_image);

        parms[20] = new SqlParameter(content_images_DT.Enum_content_images_DT.small_image.ToString(), obj.small_image);

        parms[21] = new SqlParameter(content_images_DT.Enum_content_images_DT.size.ToString(), obj.size);

        parms[22] = new SqlParameter(content_images_DT.Enum_content_images_DT.record_date_georgian.ToString(), obj.record_date_georgian);

        parms[23] = new SqlParameter(content_images_DT.Enum_content_images_DT.record_date_hijri.ToString(), obj.record_date_hijri);

        parms[24] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_file.ToString(), obj.form_file);

        parms[25] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_file_en.ToString(), obj.form_file_en);

        parms[26] = new SqlParameter(content_images_DT.Enum_content_images_DT.form_file_fr.ToString(), obj.form_file_fr);
        parms[27] = new SqlParameter(content_images_DT.Enum_content_images_DT.period_id_multi.ToString(), obj.period_id_multi);
        
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(content_images_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "content_images_Save", parms);

             	    obj.id = Convert.ToInt32(parms[2].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int content_images_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "content_images_Delete", content_images_ID);
                return content_images_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "content_images_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static content_images_DT SelectByID(int content_images_ID)
        {
            try
            {
              if (content_images_ID > 0)
                {
                SqlDataReader drTableName;
                content_images_DT oInfo_content_images_DT = new content_images_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "content_images_Select", content_images_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_content_images_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_content_images_DT;
               }
                else
                    return new content_images_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

