//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		content_media_DB
// Date Generated:	05-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class content_media_DB
    {

        #region "Private methods"

        private static content_media_DT FillInfoObject(SqlDataReader dr)
        {

           content_media_DT obj_content_media_DT = new content_media_DT();

           
		obj_content_media_DT.highlight = dr[content_media_DT.Enum_content_media_DT.highlight.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.highlight.ToString()]);
		obj_content_media_DT.highlight_panorama = dr[content_media_DT.Enum_content_media_DT.highlight_panorama.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.highlight_panorama.ToString()]);
		obj_content_media_DT.id = Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.id.ToString()]);
		obj_content_media_DT.content_id = dr[content_media_DT.Enum_content_media_DT.content_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.content_id.ToString()]);
		obj_content_media_DT.content_type = dr[content_media_DT.Enum_content_media_DT.content_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.content_type.ToString()]);
		obj_content_media_DT.content_media_type = dr[content_media_DT.Enum_content_media_DT.content_media_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.content_media_type.ToString()]);
		obj_content_media_DT.assigned_to = dr[content_media_DT.Enum_content_media_DT.assigned_to.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.assigned_to.ToString()]);
		obj_content_media_DT.form_status = dr[content_media_DT.Enum_content_media_DT.form_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.form_status.ToString()]);
		obj_content_media_DT.form_status_fr = dr[content_media_DT.Enum_content_media_DT.form_status_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.form_status_fr.ToString()]);
		obj_content_media_DT.form_lock_fr = dr[content_media_DT.Enum_content_media_DT.form_lock_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.form_lock_fr.ToString()]);
		obj_content_media_DT.file_status = dr[content_media_DT.Enum_content_media_DT.file_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.file_status.ToString()]);
		obj_content_media_DT.form_lock = dr[content_media_DT.Enum_content_media_DT.form_lock.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.form_lock.ToString()]);
		obj_content_media_DT.lock_files = dr[content_media_DT.Enum_content_media_DT.lock_files.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.lock_files.ToString()]);
		obj_content_media_DT.period_id = dr[content_media_DT.Enum_content_media_DT.period_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.period_id.ToString()]);
		obj_content_media_DT.form_status_en = dr[content_media_DT.Enum_content_media_DT.form_status_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.form_status_en.ToString()]);
		obj_content_media_DT.form_lock_en = dr[content_media_DT.Enum_content_media_DT.form_lock_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[content_media_DT.Enum_content_media_DT.form_lock_en.ToString()]);
		obj_content_media_DT.period_desc = dr[content_media_DT.Enum_content_media_DT.period_desc.ToString()] == DBNull.Value ? null : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.period_desc.ToString()]);
		obj_content_media_DT.file_name = dr[content_media_DT.Enum_content_media_DT.file_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.file_name.ToString()]);
		obj_content_media_DT.extension = dr[content_media_DT.Enum_content_media_DT.extension.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.extension.ToString()]);
		obj_content_media_DT.file_type = dr[content_media_DT.Enum_content_media_DT.file_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.file_type.ToString()]);
		obj_content_media_DT.size = dr[content_media_DT.Enum_content_media_DT.size.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.size.ToString()]);
		obj_content_media_DT.record_place = dr[content_media_DT.Enum_content_media_DT.record_place.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.record_place.ToString()]);
		obj_content_media_DT.record_date_georgian = dr[content_media_DT.Enum_content_media_DT.record_date_georgian.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.record_date_georgian.ToString()]);
		obj_content_media_DT.record_date_hijri = dr[content_media_DT.Enum_content_media_DT.record_date_hijri.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.record_date_hijri.ToString()]);
		obj_content_media_DT.form_file = dr[content_media_DT.Enum_content_media_DT.form_file.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.form_file.ToString()]);
		obj_content_media_DT.small_image = dr[content_media_DT.Enum_content_media_DT.small_image.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.small_image.ToString()]);
		obj_content_media_DT.form_file_en = dr[content_media_DT.Enum_content_media_DT.form_file_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.form_file_en.ToString()]);
		obj_content_media_DT.form_file_fr = dr[content_media_DT.Enum_content_media_DT.form_file_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.form_file_fr.ToString()]);
        obj_content_media_DT.period_id_multi = dr[content_media_DT.Enum_content_media_DT.period_id_multi.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_media_DT.Enum_content_media_DT.period_id_multi.ToString()]);
		
           return obj_content_media_DT;
        }

        private static SqlParameter[] GetParameters(content_media_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[29];
           
			

        parms[0] = new SqlParameter(content_media_DT.Enum_content_media_DT.highlight.ToString(), obj.highlight);

        parms[1] = new SqlParameter(content_media_DT.Enum_content_media_DT.highlight_panorama.ToString(), obj.highlight_panorama);
        

        parms[2] = new SqlParameter(content_media_DT.Enum_content_media_DT.id.ToString(), obj.id);
        parms[2].Direction = ParameterDirection.InputOutput;

        parms[3] = new SqlParameter(content_media_DT.Enum_content_media_DT.content_id.ToString(), obj.content_id);

        parms[4] = new SqlParameter(content_media_DT.Enum_content_media_DT.content_type.ToString(), obj.content_type);

        parms[5] = new SqlParameter(content_media_DT.Enum_content_media_DT.content_media_type.ToString(), obj.content_media_type);

        parms[6] = new SqlParameter(content_media_DT.Enum_content_media_DT.assigned_to.ToString(), obj.assigned_to);

        parms[7] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_status.ToString(), obj.form_status);

        parms[8] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_status_fr.ToString(), obj.form_status_fr);

        parms[9] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_lock_fr.ToString(), obj.form_lock_fr);

        parms[10] = new SqlParameter(content_media_DT.Enum_content_media_DT.file_status.ToString(), obj.file_status);

        parms[11] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_lock.ToString(), obj.form_lock);

        parms[12] = new SqlParameter(content_media_DT.Enum_content_media_DT.lock_files.ToString(), obj.lock_files);

        parms[13] = new SqlParameter(content_media_DT.Enum_content_media_DT.period_id.ToString(), obj.period_id);

        parms[14] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_status_en.ToString(), obj.form_status_en);

        parms[15] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_lock_en.ToString(), obj.form_lock_en);

        parms[16] = new SqlParameter(content_media_DT.Enum_content_media_DT.period_desc.ToString(), obj.period_desc);

        parms[17] = new SqlParameter(content_media_DT.Enum_content_media_DT.file_name.ToString(), obj.file_name);

        parms[18] = new SqlParameter(content_media_DT.Enum_content_media_DT.extension.ToString(), obj.extension);

        parms[19] = new SqlParameter(content_media_DT.Enum_content_media_DT.file_type.ToString(), obj.file_type);

        parms[20] = new SqlParameter(content_media_DT.Enum_content_media_DT.size.ToString(), obj.size);

        parms[21] = new SqlParameter(content_media_DT.Enum_content_media_DT.record_place.ToString(), obj.record_place);

        parms[22] = new SqlParameter(content_media_DT.Enum_content_media_DT.record_date_georgian.ToString(), obj.record_date_georgian);

        parms[23] = new SqlParameter(content_media_DT.Enum_content_media_DT.record_date_hijri.ToString(), obj.record_date_hijri);

        parms[24] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_file.ToString(), obj.form_file);

        parms[25] = new SqlParameter(content_media_DT.Enum_content_media_DT.small_image.ToString(), obj.small_image);

        parms[26] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_file_en.ToString(), obj.form_file_en);

        parms[27] = new SqlParameter(content_media_DT.Enum_content_media_DT.form_file_fr.ToString(), obj.form_file_fr);
        parms[28] = new SqlParameter(content_media_DT.Enum_content_media_DT.period_id_multi.ToString(), obj.period_id_multi);
           
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(content_media_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "content_media_Save", parms);

             	    obj.id = Convert.ToInt32(parms[2].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int content_media_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "content_media_Delete", content_media_ID);
                return content_media_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "content_media_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static content_media_DT SelectByID(int content_media_ID)
        {
            try
            {
              if (content_media_ID > 0)
                {
                SqlDataReader drTableName;
                content_media_DT oInfo_content_media_DT = new content_media_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "content_media_Select", content_media_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_content_media_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_content_media_DT;
               }
                else
                    return new content_media_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

