//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		content_status_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class content_status_DB
    {

        #region "Private methods"

        private static content_status_DT FillInfoObject(SqlDataReader dr)
        {

           content_status_DT obj_content_status_DT = new content_status_DT();

           
		obj_content_status_DT.id = Convert.ToInt32(dr[content_status_DT.Enum_content_status_DT.id.ToString()]);
		obj_content_status_DT.title = dr[content_status_DT.Enum_content_status_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[content_status_DT.Enum_content_status_DT.title.ToString()]);

           return obj_content_status_DT;
        }

        private static SqlParameter[] GetParameters(content_status_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[2];
           
			
        

        parms[0] = new SqlParameter(content_status_DT.Enum_content_status_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(content_status_DT.Enum_content_status_DT.title.ToString(), obj.title);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(content_status_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "content_status_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int content_status_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "content_status_Delete", content_status_ID);
                return content_status_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "content_status_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static content_status_DT SelectByID(int content_status_ID)
        {
            try
            {
                SqlDataReader drTableName;
                content_status_DT oInfo_content_status_DT = new content_status_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "content_status_Select", content_status_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_content_status_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_content_status_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

