//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		esnad_type_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class esnad_type_DB
    {

        #region "Private methods"

        private static esnad_type_DT FillInfoObject(SqlDataReader dr)
        {

           esnad_type_DT obj_esnad_type_DT = new esnad_type_DT();

           
		obj_esnad_type_DT.id = Convert.ToInt32(dr[esnad_type_DT.Enum_esnad_type_DT.id.ToString()]);
		obj_esnad_type_DT.title = dr[esnad_type_DT.Enum_esnad_type_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[esnad_type_DT.Enum_esnad_type_DT.title.ToString()]);
		obj_esnad_type_DT.the_key = dr[esnad_type_DT.Enum_esnad_type_DT.the_key.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[esnad_type_DT.Enum_esnad_type_DT.the_key.ToString()]);

           return obj_esnad_type_DT;
        }

        private static SqlParameter[] GetParameters(esnad_type_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(esnad_type_DT.Enum_esnad_type_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(esnad_type_DT.Enum_esnad_type_DT.title.ToString(), obj.title);

        parms[2] = new SqlParameter(esnad_type_DT.Enum_esnad_type_DT.the_key.ToString(), obj.the_key);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(esnad_type_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "esnad_type_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int esnad_type_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "esnad_type_Delete", esnad_type_ID);
                return esnad_type_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "esnad_type_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static esnad_type_DT SelectByID(int esnad_type_ID)
        {
            try
            {
                SqlDataReader drTableName;
                esnad_type_DT oInfo_esnad_type_DT = new esnad_type_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "esnad_type_Select", esnad_type_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_esnad_type_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_esnad_type_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

