//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		file_usage_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class file_usage_DB
    {

        #region "Private methods"

        private static file_usage_DT FillInfoObject(SqlDataReader dr)
        {

           file_usage_DT obj_file_usage_DT = new file_usage_DT();

           
		obj_file_usage_DT.id = dr[file_usage_DT.Enum_file_usage_DT.id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[file_usage_DT.Enum_file_usage_DT.id.ToString()]);
		obj_file_usage_DT.title = dr[file_usage_DT.Enum_file_usage_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[file_usage_DT.Enum_file_usage_DT.title.ToString()]);

           return obj_file_usage_DT;
        }

        private static SqlParameter[] GetParameters(file_usage_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[2];
           
			

        parms[0] = new SqlParameter(file_usage_DT.Enum_file_usage_DT.id.ToString(), obj.id);

        parms[1] = new SqlParameter(file_usage_DT.Enum_file_usage_DT.title.ToString(), obj.title);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(file_usage_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "file_usage_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int file_usage_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "file_usage_Delete", file_usage_ID);
                return file_usage_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "file_usage_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static file_usage_DT SelectByID(int file_usage_ID)
        {
            try
            {
                SqlDataReader drTableName;
                file_usage_DT oInfo_file_usage_DT = new file_usage_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "file_usage_Select", file_usage_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_file_usage_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_file_usage_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

