//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		languages_DB
// Date Generated:	16-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class languages_DB
    {

        #region "Private methods"

        private static languages_DT FillInfoObject(SqlDataReader dr)
        {

           languages_DT obj_languages_DT = new languages_DT();

           
		obj_languages_DT.id = Convert.ToInt32(dr[languages_DT.Enum_languages_DT.id.ToString()]);
		obj_languages_DT.title_ar = dr[languages_DT.Enum_languages_DT.title_ar.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[languages_DT.Enum_languages_DT.title_ar.ToString()]);
		obj_languages_DT.title_en = dr[languages_DT.Enum_languages_DT.title_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[languages_DT.Enum_languages_DT.title_en.ToString()]);
		obj_languages_DT.title_fr = dr[languages_DT.Enum_languages_DT.title_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[languages_DT.Enum_languages_DT.title_fr.ToString()]);

           return obj_languages_DT;
        }

        private static SqlParameter[] GetParameters(languages_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[4];
           
			
        

        parms[0] = new SqlParameter(languages_DT.Enum_languages_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(languages_DT.Enum_languages_DT.title_ar.ToString(), obj.title_ar);

        parms[2] = new SqlParameter(languages_DT.Enum_languages_DT.title_en.ToString(), obj.title_en);

        parms[3] = new SqlParameter(languages_DT.Enum_languages_DT.title_fr.ToString(), obj.title_fr);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(languages_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "languages_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int languages_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "languages_Delete", languages_ID);
                return languages_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "languages_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static languages_DT SelectByID(int languages_ID)
        {
            try
            {
              if (languages_ID > 0)
                {
                SqlDataReader drTableName;
                languages_DT oInfo_languages_DT = new languages_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "languages_Select", languages_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_languages_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_languages_DT;
               }
                else
                    return new languages_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

