//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		manuscripts_details_DB
// Date Generated:	02-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class manuscripts_details_DB
    {

        #region "Private methods"

        private static manuscripts_details_DT FillInfoObject(SqlDataReader dr)
        {

            manuscripts_details_DT obj_manuscripts_details_DT = new manuscripts_details_DT();


            obj_manuscripts_details_DT.id = Convert.ToInt32(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.id.ToString()]);
            obj_manuscripts_details_DT.manuscript_id = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.manuscript_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.manuscript_id.ToString()]);
            obj_manuscripts_details_DT.lang_id = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.lang_id.ToString()]);
            obj_manuscripts_details_DT.period_id = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.period_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.period_id.ToString()]);
            obj_manuscripts_details_DT.keywords = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.keywords.ToString()] == DBNull.Value ? null : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.keywords.ToString()]);
            obj_manuscripts_details_DT.notes = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.notes.ToString()]);
            obj_manuscripts_details_DT.period_notes = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.period_notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.period_notes.ToString()]);
            obj_manuscripts_details_DT.title = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title.ToString()]);
            obj_manuscripts_details_DT.author = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author.ToString()]);
            obj_manuscripts_details_DT.title_src = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_src.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_src.ToString()]);
            obj_manuscripts_details_DT.author_src = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_src.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_src.ToString()]);
            obj_manuscripts_details_DT.man_lang = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.man_lang.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.man_lang.ToString()]);
            obj_manuscripts_details_DT.copy_place = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_place.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_place.ToString()]);
            obj_manuscripts_details_DT.author_intro = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_intro.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_intro.ToString()]);
            obj_manuscripts_details_DT.author_mosk = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_mosk.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_mosk.ToString()]);
            obj_manuscripts_details_DT.title_fromtitle = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_fromtitle.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_fromtitle.ToString()]);
            obj_manuscripts_details_DT.title_intro = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_intro.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_intro.ToString()]);
            obj_manuscripts_details_DT.title_mosk = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_mosk.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.title_mosk.ToString()]);
            obj_manuscripts_details_DT.listinging = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.listinging.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.listinging.ToString()]);
            obj_manuscripts_details_DT.data_collector_name = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_collector_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_collector_name.ToString()]);
            obj_manuscripts_details_DT.data_revision_name = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_revision_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_revision_name.ToString()]);
            obj_manuscripts_details_DT.data_entry_name = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_entry_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_entry_name.ToString()]);
            obj_manuscripts_details_DT.data_entry_revision_name = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_entry_revision_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.data_entry_revision_name.ToString()]);
            obj_manuscripts_details_DT.author_fromtitle = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_fromtitle.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.author_fromtitle.ToString()]);
            obj_manuscripts_details_DT.license_type = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.license_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.license_type.ToString()]);
            obj_manuscripts_details_DT.oldest_license_date = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date.ToString()]);
            obj_manuscripts_details_DT.oldest_license_date_m = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date_m.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date_m.ToString()]);
            obj_manuscripts_details_DT.oldest_license_date_h = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date_h.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date_h.ToString()]);
            obj_manuscripts_details_DT.listinging_date_m = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.listinging_date_m.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.listinging_date_m.ToString()]);
            obj_manuscripts_details_DT.listinging_date_h = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.listinging_date_h.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.listinging_date_h.ToString()]);
            obj_manuscripts_details_DT.country = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.country.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.country.ToString()]);
            obj_manuscripts_details_DT.town = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.town.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.town.ToString()]);
            obj_manuscripts_details_DT.general_no = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.general_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.general_no.ToString()]);
            obj_manuscripts_details_DT.special_no = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.special_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.special_no.ToString()]);
            obj_manuscripts_details_DT.the_art = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.the_art.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.the_art.ToString()]);
            obj_manuscripts_details_DT.special_lib = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.special_lib.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.special_lib.ToString()]);
            obj_manuscripts_details_DT.ruler = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.ruler.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.ruler.ToString()]);
            obj_manuscripts_details_DT.copy_contains = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_contains.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_contains.ToString()]);
            obj_manuscripts_details_DT.font_type = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.font_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.font_type.ToString()]);
            obj_manuscripts_details_DT.copy_has = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_has.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_has.ToString()]);
            obj_manuscripts_details_DT.introduction = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.introduction.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.introduction.ToString()]);
            obj_manuscripts_details_DT.conclusion = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.conclusion.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.conclusion.ToString()]);
            obj_manuscripts_details_DT.papers_to = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.papers_to.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.papers_to.ToString()]);
            obj_manuscripts_details_DT.parts_no = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.parts_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.parts_no.ToString()]);
            obj_manuscripts_details_DT.folders_no = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.folders_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.folders_no.ToString()]);
            obj_manuscripts_details_DT.height = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.height.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.height.ToString()]);
            obj_manuscripts_details_DT.length = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.length.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.length.ToString()]);
            obj_manuscripts_details_DT.width = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.width.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.width.ToString()]);
            obj_manuscripts_details_DT.copier = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copier.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copier.ToString()]);
            obj_manuscripts_details_DT.copy_date = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_date.ToString()]);
            obj_manuscripts_details_DT.copy_date_type = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_date_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_date_type.ToString()]);
            obj_manuscripts_details_DT.copy_state = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_state.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.copy_state.ToString()]);
            obj_manuscripts_details_DT.collection_no = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.collection_no.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.collection_no.ToString()]);
            obj_manuscripts_details_DT.papers_from = dr[manuscripts_details_DT.Enum_manuscripts_details_DT.papers_from.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[manuscripts_details_DT.Enum_manuscripts_details_DT.papers_from.ToString()]);
	    



            return obj_manuscripts_details_DT;
        }

        private static SqlParameter[] GetParameters(manuscripts_details_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[54];




            parms[0] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.id.ToString(), obj.id);
            parms[0].Direction = ParameterDirection.InputOutput;

            parms[1] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.manuscript_id.ToString(), obj.manuscript_id);

            parms[2] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.lang_id.ToString(), obj.lang_id);

            parms[3] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.period_id.ToString(), obj.period_id);

            parms[4] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.keywords.ToString(), obj.keywords);

            parms[5] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.notes.ToString(), obj.notes);

            parms[6] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.period_notes.ToString(), obj.period_notes);

            parms[7] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.title.ToString(), obj.title);

            parms[8] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.author.ToString(), obj.author);

            parms[9] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.title_src.ToString(), obj.title_src);

            parms[10] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.author_src.ToString(), obj.author_src);

            parms[11] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.man_lang.ToString(), obj.man_lang);

            parms[12] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copy_place.ToString(), obj.copy_place);

            parms[13] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.author_intro.ToString(), obj.author_intro);

            parms[14] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.author_mosk.ToString(), obj.author_mosk);

            parms[15] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.title_fromtitle.ToString(), obj.title_fromtitle);

            parms[16] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.title_intro.ToString(), obj.title_intro);

            parms[17] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.title_mosk.ToString(), obj.title_mosk);

            parms[18] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.listinging.ToString(), obj.listinging);

            parms[19] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.data_collector_name.ToString(), obj.data_collector_name);

            parms[20] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.data_revision_name.ToString(), obj.data_revision_name);

            parms[21] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.data_entry_name.ToString(), obj.data_entry_name);

            parms[22] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.data_entry_revision_name.ToString(), obj.data_entry_revision_name);

            parms[23] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.author_fromtitle.ToString(), obj.author_fromtitle);

            parms[24] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.license_type.ToString(), obj.license_type);

            parms[25] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date.ToString(), obj.oldest_license_date);

            parms[26] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date_m.ToString(), obj.oldest_license_date_m);

            parms[27] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.oldest_license_date_h.ToString(), obj.oldest_license_date_h);

            parms[28] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.listinging_date_m.ToString(), obj.listinging_date_m);

            parms[29] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.listinging_date_h.ToString(), obj.listinging_date_h);

            parms[30] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.country.ToString(), obj.country);

            parms[31] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.town.ToString(), obj.town);

            parms[32] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.general_no.ToString(), obj.general_no);

            parms[33] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.special_no.ToString(), obj.special_no);

            parms[34] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.the_art.ToString(), obj.the_art);

            parms[35] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.special_lib.ToString(), obj.special_lib);

            parms[36] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.ruler.ToString(), obj.ruler);

            parms[37] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copy_contains.ToString(), obj.copy_contains);

            parms[38] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.font_type.ToString(), obj.font_type);

            parms[39] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copy_has.ToString(), obj.copy_has);

            parms[40] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.introduction.ToString(), obj.introduction);

            parms[41] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.conclusion.ToString(), obj.conclusion);

            parms[42] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.papers_to.ToString(), obj.papers_to);

            parms[43] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.parts_no.ToString(), obj.parts_no);

            parms[44] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.folders_no.ToString(), obj.folders_no);

            parms[45] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.height.ToString(), obj.height);

            parms[46] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.length.ToString(), obj.length);

            parms[47] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.width.ToString(), obj.width);

            parms[48] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copier.ToString(), obj.copier);

            parms[49] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copy_date.ToString(), obj.copy_date);

            parms[50] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copy_date_type.ToString(), obj.copy_date_type);

            parms[51] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.copy_state.ToString(), obj.copy_state);

            parms[52] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.collection_no.ToString(), obj.collection_no);

            parms[53] = new SqlParameter(manuscripts_details_DT.Enum_manuscripts_details_DT.papers_from.ToString(), obj.papers_from);
	    
	    
            return parms;
        }


        #endregion

	    #region "DB methods"

        public static int Save(manuscripts_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "manuscripts_details_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int manuscripts_details_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "manuscripts_details_Delete", manuscripts_details_ID);
                return manuscripts_details_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "manuscripts_details_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static manuscripts_details_DT SelectByID(int manuscripts_details_ID,int lang_id)
        {
            try
            {
              if (manuscripts_details_ID > 0)
                {
                SqlDataReader drTableName;
                manuscripts_details_DT oInfo_manuscripts_details_DT = new manuscripts_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "manuscripts_details_Select", manuscripts_details_ID, lang_id);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_manuscripts_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_manuscripts_details_DT;
               }
                else
                    return new manuscripts_details_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

