//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_evolution_DB
// Date Generated:	11-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class places_evolution_DB
    {

        #region "Private methods"

        private static places_evolution_DT FillInfoObject(SqlDataReader dr)
        {

           places_evolution_DT obj_places_evolution_DT = new places_evolution_DT();

           
		obj_places_evolution_DT.id = Convert.ToInt32(dr[places_evolution_DT.Enum_places_evolution_DT.id.ToString()]);
		obj_places_evolution_DT.place_id = dr[places_evolution_DT.Enum_places_evolution_DT.place_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_evolution_DT.Enum_places_evolution_DT.place_id.ToString()]);
		obj_places_evolution_DT.architectural_evolution_age = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_age.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_age.ToString()]);
		obj_places_evolution_DT.architectural_evolution_desc = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc.ToString()]);
		obj_places_evolution_DT.architectural_evolution_desc_en = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc_en.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc_en.ToString()]);
		obj_places_evolution_DT.architectural_evolution_desc_fr = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc_fr.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc_fr.ToString()]);
		obj_places_evolution_DT.architectural_evolution_note = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_note.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_note.ToString()]);
		obj_places_evolution_DT.architectural_evolution_georg_date = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_georg_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_georg_date.ToString()]);
		obj_places_evolution_DT.architectural_evolution_hijri_date = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_hijri_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_hijri_date.ToString()]);
		obj_places_evolution_DT.architectural_evolution_person = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person.ToString()]);
		obj_places_evolution_DT.architectural_evolution_person_en = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person_en.ToString()]);
		obj_places_evolution_DT.architectural_evolution_person_fr = dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person_fr.ToString()]);

           return obj_places_evolution_DT;
        }

        private static SqlParameter[] GetParameters(places_evolution_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[12];
           
			
        

        parms[0] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.place_id.ToString(), obj.place_id);

        parms[2] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_age.ToString(), obj.architectural_evolution_age);

        parms[3] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc.ToString(), obj.architectural_evolution_desc);

        parms[4] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc_en.ToString(), obj.architectural_evolution_desc_en);

        parms[5] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_desc_fr.ToString(), obj.architectural_evolution_desc_fr);

        parms[6] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_note.ToString(), obj.architectural_evolution_note);

        parms[7] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_georg_date.ToString(), obj.architectural_evolution_georg_date);

        parms[8] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_hijri_date.ToString(), obj.architectural_evolution_hijri_date);

        parms[9] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person.ToString(), obj.architectural_evolution_person);

        parms[10] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person_en.ToString(), obj.architectural_evolution_person_en);

        parms[11] = new SqlParameter(places_evolution_DT.Enum_places_evolution_DT.architectural_evolution_person_fr.ToString(), obj.architectural_evolution_person_fr);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(places_evolution_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "places_evolution_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int places_evolution_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "places_evolution_Delete", places_evolution_ID);
                return places_evolution_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "places_evolution_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static places_evolution_DT SelectByID(int places_evolution_ID)
        {
            try
            {
              if (places_evolution_ID > 0)
                {
                SqlDataReader drTableName;
                places_evolution_DT oInfo_places_evolution_DT = new places_evolution_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "places_evolution_Select", places_evolution_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_places_evolution_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_places_evolution_DT;
               }
                else
                    return new places_evolution_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

