//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_building_material_DB
// Date Generated:	25-03-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class places_building_material_DB
    {

        #region "Private methods"

        private static places_building_material_DT FillInfoObject(SqlDataReader dr)
        {

           places_building_material_DT obj_places_building_material_DT = new places_building_material_DT();

           
		obj_places_building_material_DT.id = Convert.ToInt32(dr[places_building_material_DT.Enum_places_building_material_DT.id.ToString()]);
		obj_places_building_material_DT.place_id = dr[places_building_material_DT.Enum_places_building_material_DT.place_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_building_material_DT.Enum_places_building_material_DT.place_id.ToString()]);
		obj_places_building_material_DT.building_raw_material = dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material.ToString()]);
		obj_places_building_material_DT.building_raw_material_use = dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_use.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_use.ToString()]);
		obj_places_building_material_DT.building_raw_material_notes = dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_notes.ToString()]);
		obj_places_building_material_DT.building_raw_material_other = dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_other.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_other.ToString()]);
		obj_places_building_material_DT.building_raw_material_use_other = dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_use_other.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[places_building_material_DT.Enum_places_building_material_DT.building_raw_material_use_other.ToString()]);

           return obj_places_building_material_DT;
        }

        private static SqlParameter[] GetParameters(places_building_material_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[7];
           
			
        

        parms[0] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.place_id.ToString(), obj.place_id);

        parms[2] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.building_raw_material.ToString(), obj.building_raw_material);

        parms[3] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.building_raw_material_use.ToString(), obj.building_raw_material_use);

        parms[4] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.building_raw_material_notes.ToString(), obj.building_raw_material_notes);

        parms[5] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.building_raw_material_other.ToString(), obj.building_raw_material_other);

        parms[6] = new SqlParameter(places_building_material_DT.Enum_places_building_material_DT.building_raw_material_use_other.ToString(), obj.building_raw_material_use_other);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(places_building_material_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "places_building_material_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int places_building_material_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "places_building_material_Delete", places_building_material_ID);
                return places_building_material_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "places_building_material_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static places_building_material_DT SelectByID(int places_building_material_ID)
        {
            try
            {
              if (places_building_material_ID > 0)
                {
                SqlDataReader drTableName;
                places_building_material_DT oInfo_places_building_material_DT = new places_building_material_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "places_building_material_Select", places_building_material_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_places_building_material_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_places_building_material_DT;
               }
                else
                    return new places_building_material_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

