//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_address_DB
// Date Generated:	11-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class places_address_DB
    {

        #region "Private methods"

        private static places_address_DT FillInfoObject(SqlDataReader dr)
        {

           places_address_DT obj_places_address_DT = new places_address_DT();

           
		obj_places_address_DT.id = Convert.ToInt32(dr[places_address_DT.Enum_places_address_DT.id.ToString()]);
		obj_places_address_DT.place_id = dr[places_address_DT.Enum_places_address_DT.place_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_address_DT.Enum_places_address_DT.place_id.ToString()]);
		obj_places_address_DT.address_age = dr[places_address_DT.Enum_places_address_DT.address_age.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[places_address_DT.Enum_places_address_DT.address_age.ToString()]);
		obj_places_address_DT.address_age_desc = dr[places_address_DT.Enum_places_address_DT.address_age_desc.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_address_DT.Enum_places_address_DT.address_age_desc.ToString()]);
		obj_places_address_DT.address_age_desc_en = dr[places_address_DT.Enum_places_address_DT.address_age_desc_en.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_address_DT.Enum_places_address_DT.address_age_desc_en.ToString()]);
		obj_places_address_DT.address_age_desc_fr = dr[places_address_DT.Enum_places_address_DT.address_age_desc_fr.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_address_DT.Enum_places_address_DT.address_age_desc_fr.ToString()]);
		obj_places_address_DT.address_age_note = dr[places_address_DT.Enum_places_address_DT.address_age_note.ToString()] == DBNull.Value ? null : Convert.ToString(dr[places_address_DT.Enum_places_address_DT.address_age_note.ToString()]);

           return obj_places_address_DT;
        }

        private static SqlParameter[] GetParameters(places_address_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[7];
           
			
        

        parms[0] = new SqlParameter(places_address_DT.Enum_places_address_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(places_address_DT.Enum_places_address_DT.place_id.ToString(), obj.place_id);

        parms[2] = new SqlParameter(places_address_DT.Enum_places_address_DT.address_age.ToString(), obj.address_age);

        parms[3] = new SqlParameter(places_address_DT.Enum_places_address_DT.address_age_desc.ToString(), obj.address_age_desc);

        parms[4] = new SqlParameter(places_address_DT.Enum_places_address_DT.address_age_desc_en.ToString(), obj.address_age_desc_en);

        parms[5] = new SqlParameter(places_address_DT.Enum_places_address_DT.address_age_desc_fr.ToString(), obj.address_age_desc_fr);

        parms[6] = new SqlParameter(places_address_DT.Enum_places_address_DT.address_age_note.ToString(), obj.address_age_note);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(places_address_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "places_address_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int places_address_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "places_address_Delete", places_address_ID);
                return places_address_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "places_address_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static places_address_DT SelectByID(int places_address_ID)
        {
            try
            {
              if (places_address_ID > 0)
                {
                SqlDataReader drTableName;
                places_address_DT oInfo_places_address_DT = new places_address_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "places_address_Select", places_address_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_places_address_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_places_address_DT;
               }
                else
                    return new places_address_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

