//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		publishers_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class publishers_DB
    {

        #region "Private methods"

        private static publishers_DT FillInfoObject(SqlDataReader dr)
        {

           publishers_DT obj_publishers_DT = new publishers_DT();

           
		obj_publishers_DT.id = Convert.ToInt32(dr[publishers_DT.Enum_publishers_DT.id.ToString()]);
		obj_publishers_DT.title_ar = dr[publishers_DT.Enum_publishers_DT.title_ar.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[publishers_DT.Enum_publishers_DT.title_ar.ToString()]);
		obj_publishers_DT.title_en = dr[publishers_DT.Enum_publishers_DT.title_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[publishers_DT.Enum_publishers_DT.title_en.ToString()]);
		obj_publishers_DT.title_fr = dr[publishers_DT.Enum_publishers_DT.title_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[publishers_DT.Enum_publishers_DT.title_fr.ToString()]);

           return obj_publishers_DT;
        }

        private static SqlParameter[] GetParameters(publishers_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[4];
           
			
        

        parms[0] = new SqlParameter(publishers_DT.Enum_publishers_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(publishers_DT.Enum_publishers_DT.title_ar.ToString(), obj.title_ar);

        parms[2] = new SqlParameter(publishers_DT.Enum_publishers_DT.title_en.ToString(), obj.title_en);

        parms[3] = new SqlParameter(publishers_DT.Enum_publishers_DT.title_fr.ToString(), obj.title_fr);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(publishers_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "publishers_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int publishers_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "publishers_Delete", publishers_ID);
                return publishers_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "publishers_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static publishers_DT SelectByID(int publishers_ID)
        {
            try
            {
                SqlDataReader drTableName;
                publishers_DT oInfo_publishers_DT = new publishers_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "publishers_Select", publishers_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_publishers_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_publishers_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

