//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		tags_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class tags_DB
    {

        #region "Private methods"

        private static tags_DT FillInfoObject(SqlDataReader dr)
        {

           tags_DT obj_tags_DT = new tags_DT();

           
		obj_tags_DT.id = Convert.ToInt32(dr[tags_DT.Enum_tags_DT.id.ToString()]);
		obj_tags_DT.tag_type = dr[tags_DT.Enum_tags_DT.tag_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[tags_DT.Enum_tags_DT.tag_type.ToString()]);
		obj_tags_DT.title_ar = dr[tags_DT.Enum_tags_DT.title_ar.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tags_DT.Enum_tags_DT.title_ar.ToString()]);
		obj_tags_DT.title_en = dr[tags_DT.Enum_tags_DT.title_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tags_DT.Enum_tags_DT.title_en.ToString()]);
		obj_tags_DT.title_fr = dr[tags_DT.Enum_tags_DT.title_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tags_DT.Enum_tags_DT.title_fr.ToString()]);

           return obj_tags_DT;
        }

        private static SqlParameter[] GetParameters(tags_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[5];
           
			
        

        parms[0] = new SqlParameter(tags_DT.Enum_tags_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(tags_DT.Enum_tags_DT.tag_type.ToString(), obj.tag_type);

        parms[2] = new SqlParameter(tags_DT.Enum_tags_DT.title_ar.ToString(), obj.title_ar);

        parms[3] = new SqlParameter(tags_DT.Enum_tags_DT.title_en.ToString(), obj.title_en);

        parms[4] = new SqlParameter(tags_DT.Enum_tags_DT.title_fr.ToString(), obj.title_fr);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(tags_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "tags_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int tags_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "tags_Delete", tags_ID);
                return tags_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "tags_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static tags_DT SelectByID(int tags_ID)
        {
            try
            {
                SqlDataReader drTableName;
                tags_DT oInfo_tags_DT = new tags_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "tags_Select", tags_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_tags_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_tags_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

