//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		takreezat_details_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class takreezat_details_DB
    {

        #region "Private methods"

        private static takreezat_details_DT FillInfoObject(SqlDataReader dr)
        {

           takreezat_details_DT obj_takreezat_details_DT = new takreezat_details_DT();

           
		obj_takreezat_details_DT.id = Convert.ToInt32(dr[takreezat_details_DT.Enum_takreezat_details_DT.id.ToString()]);
		obj_takreezat_details_DT.takreezat_id = dr[takreezat_details_DT.Enum_takreezat_details_DT.takreezat_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[takreezat_details_DT.Enum_takreezat_details_DT.takreezat_id.ToString()]);
		obj_takreezat_details_DT.lang_id = dr[takreezat_details_DT.Enum_takreezat_details_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[takreezat_details_DT.Enum_takreezat_details_DT.lang_id.ToString()]);
		obj_takreezat_details_DT.details = dr[takreezat_details_DT.Enum_takreezat_details_DT.details.ToString()] == DBNull.Value ? null : Convert.ToString(dr[takreezat_details_DT.Enum_takreezat_details_DT.details.ToString()]);
		obj_takreezat_details_DT.title = dr[takreezat_details_DT.Enum_takreezat_details_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[takreezat_details_DT.Enum_takreezat_details_DT.title.ToString()]);

           return obj_takreezat_details_DT;
        }

        private static SqlParameter[] GetParameters(takreezat_details_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[5];
           
			
        

        parms[0] = new SqlParameter(takreezat_details_DT.Enum_takreezat_details_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(takreezat_details_DT.Enum_takreezat_details_DT.takreezat_id.ToString(), obj.takreezat_id);

        parms[2] = new SqlParameter(takreezat_details_DT.Enum_takreezat_details_DT.lang_id.ToString(), obj.lang_id);

        parms[3] = new SqlParameter(takreezat_details_DT.Enum_takreezat_details_DT.details.ToString(), obj.details);

        parms[4] = new SqlParameter(takreezat_details_DT.Enum_takreezat_details_DT.title.ToString(), obj.title);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(takreezat_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "takreezat_details_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int takreezat_details_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "takreezat_details_Delete", takreezat_details_ID);
                return takreezat_details_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "takreezat_details_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static takreezat_details_DT SelectByID(int takreezat_details_ID)
        {
            try
            {
                SqlDataReader drTableName;
                takreezat_details_DT oInfo_takreezat_details_DT = new takreezat_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "takreezat_details_Select", takreezat_details_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_takreezat_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_takreezat_details_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

