//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		takreezat_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class takreezat_DB
    {

        #region "Private methods"

        private static takreezat_DT FillInfoObject(SqlDataReader dr)
        {

           takreezat_DT obj_takreezat_DT = new takreezat_DT();

           
		obj_takreezat_DT.id = Convert.ToInt32(dr[takreezat_DT.Enum_takreezat_DT.id.ToString()]);
		obj_takreezat_DT.char_id = dr[takreezat_DT.Enum_takreezat_DT.char_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[takreezat_DT.Enum_takreezat_DT.char_id.ToString()]);
		obj_takreezat_DT.type = dr[takreezat_DT.Enum_takreezat_DT.type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[takreezat_DT.Enum_takreezat_DT.type.ToString()]);

           return obj_takreezat_DT;
        }

        private static SqlParameter[] GetParameters(takreezat_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[3];
           
			
        

        parms[0] = new SqlParameter(takreezat_DT.Enum_takreezat_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(takreezat_DT.Enum_takreezat_DT.char_id.ToString(), obj.char_id);

        parms[2] = new SqlParameter(takreezat_DT.Enum_takreezat_DT.type.ToString(), obj.type);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(takreezat_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "takreezat_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int takreezat_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "takreezat_Delete", takreezat_ID);
                return takreezat_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "takreezat_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static takreezat_DT SelectByID(int takreezat_ID)
        {
            try
            {
                SqlDataReader drTableName;
                takreezat_DT oInfo_takreezat_DT = new takreezat_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "takreezat_Select", takreezat_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_takreezat_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_takreezat_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

