//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		tamalokat_DB
// Date Generated:	24-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class tamalokat_DB
    {

        #region "Private methods"

        private static tamalokat_DT FillInfoObject(SqlDataReader dr)
        {

           tamalokat_DT obj_tamalokat_DT = new tamalokat_DT();

           
		obj_tamalokat_DT.id = Convert.ToInt32(dr[tamalokat_DT.Enum_tamalokat_DT.id.ToString()]);
		obj_tamalokat_DT.manuscript_id = dr[tamalokat_DT.Enum_tamalokat_DT.manuscript_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[tamalokat_DT.Enum_tamalokat_DT.manuscript_id.ToString()]);
		obj_tamalokat_DT.tmlkat_name = dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_name.ToString()]);
		obj_tamalokat_DT.tmlkat_date = dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_date.ToString()]);
		obj_tamalokat_DT.tmlkat_date_type = dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_date_type.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_date_type.ToString()]);
		obj_tamalokat_DT.tmlkat_name_en = dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_name_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_name_en.ToString()]);
		obj_tamalokat_DT.tmlkat_name_fr = dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_name_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tamalokat_DT.Enum_tamalokat_DT.tmlkat_name_fr.ToString()]);
        obj_tamalokat_DT.notes = dr[tamalokat_DT.Enum_tamalokat_DT.notes.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[tamalokat_DT.Enum_tamalokat_DT.notes.ToString()]);

           return obj_tamalokat_DT;
        }

        private static SqlParameter[] GetParameters(tamalokat_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[8];
           
			
        

        parms[0] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.manuscript_id.ToString(), obj.manuscript_id);

        parms[2] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.tmlkat_name.ToString(), obj.tmlkat_name);

        parms[3] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.tmlkat_date.ToString(), obj.tmlkat_date);

        parms[4] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.tmlkat_date_type.ToString(), obj.tmlkat_date_type);

        parms[5] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.tmlkat_name_en.ToString(), obj.tmlkat_name_en);

        parms[6] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.tmlkat_name_fr.ToString(), obj.tmlkat_name_fr);

        parms[7] = new SqlParameter(tamalokat_DT.Enum_tamalokat_DT.notes.ToString(), obj.notes);
        
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(tamalokat_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "tamalokat_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int tamalokat_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "tamalokat_Delete", tamalokat_ID);
                return tamalokat_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "tamalokat_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static tamalokat_DT SelectByID(int tamalokat_ID)
        {
            try
            {
              if (tamalokat_ID > 0)
                {
                SqlDataReader drTableName;
                tamalokat_DT oInfo_tamalokat_DT = new tamalokat_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "tamalokat_Select", tamalokat_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_tamalokat_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_tamalokat_DT;
               }
                else
                    return new tamalokat_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

