//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		theses_DB
// Date Generated:	08-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class theses_DB
    {

        #region "Private methods"

        private static theses_DT FillInfoObject(SqlDataReader dr)
        {

           theses_DT obj_theses_DT = new theses_DT();

           
		obj_theses_DT.highlight = dr[theses_DT.Enum_theses_DT.highlight.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.highlight.ToString()]);
		obj_theses_DT.status = dr[theses_DT.Enum_theses_DT.status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.status.ToString()]);
		obj_theses_DT.highlight_panorama = dr[theses_DT.Enum_theses_DT.highlight_panorama.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.highlight_panorama.ToString()]);
		obj_theses_DT.id = Convert.ToInt32(dr[theses_DT.Enum_theses_DT.id.ToString()]);
		obj_theses_DT.theses_type = dr[theses_DT.Enum_theses_DT.theses_type.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.theses_type.ToString()]);
		obj_theses_DT.assigned_to = dr[theses_DT.Enum_theses_DT.assigned_to.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.assigned_to.ToString()]);
		obj_theses_DT.form_status = dr[theses_DT.Enum_theses_DT.form_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.form_status.ToString()]);
		obj_theses_DT.file_status = dr[theses_DT.Enum_theses_DT.file_status.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.file_status.ToString()]);
		obj_theses_DT.form_lock = dr[theses_DT.Enum_theses_DT.form_lock.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.form_lock.ToString()]);
		obj_theses_DT.lock_files = dr[theses_DT.Enum_theses_DT.lock_files.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.lock_files.ToString()]);
		obj_theses_DT.period_id = dr[theses_DT.Enum_theses_DT.period_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.period_id.ToString()]);
		obj_theses_DT.form_status_en = dr[theses_DT.Enum_theses_DT.form_status_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.form_status_en.ToString()]);
		obj_theses_DT.form_lock_en = dr[theses_DT.Enum_theses_DT.form_lock_en.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.form_lock_en.ToString()]);
		obj_theses_DT.form_status_fr = dr[theses_DT.Enum_theses_DT.form_status_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.form_status_fr.ToString()]);
		obj_theses_DT.form_lock_fr = dr[theses_DT.Enum_theses_DT.form_lock_fr.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[theses_DT.Enum_theses_DT.form_lock_fr.ToString()]);
		obj_theses_DT.file_name = dr[theses_DT.Enum_theses_DT.file_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.file_name.ToString()]);
		obj_theses_DT.image_name = dr[theses_DT.Enum_theses_DT.image_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.image_name.ToString()]);
		obj_theses_DT.form_file = dr[theses_DT.Enum_theses_DT.form_file.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.form_file.ToString()]);
		obj_theses_DT.theses_date = dr[theses_DT.Enum_theses_DT.theses_date.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.theses_date.ToString()]);
		obj_theses_DT.theses_hdate = dr[theses_DT.Enum_theses_DT.theses_hdate.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.theses_hdate.ToString()]);
		obj_theses_DT.form_file_en = dr[theses_DT.Enum_theses_DT.form_file_en.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.form_file_en.ToString()]);
		obj_theses_DT.form_file_fr = dr[theses_DT.Enum_theses_DT.form_file_fr.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.form_file_fr.ToString()]);
        obj_theses_DT.period_id_multi = dr[theses_DT.Enum_theses_DT.period_id_multi.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[theses_DT.Enum_theses_DT.period_id_multi.ToString()]);

           return obj_theses_DT;
        }

        private static SqlParameter[] GetParameters(theses_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[23];
           
			

        parms[0] = new SqlParameter(theses_DT.Enum_theses_DT.highlight.ToString(), obj.highlight);

        parms[1] = new SqlParameter(theses_DT.Enum_theses_DT.status.ToString(), obj.status);

        parms[2] = new SqlParameter(theses_DT.Enum_theses_DT.highlight_panorama.ToString(), obj.highlight_panorama);
        

        parms[3] = new SqlParameter(theses_DT.Enum_theses_DT.id.ToString(), obj.id);
        parms[3].Direction = ParameterDirection.InputOutput;

        parms[4] = new SqlParameter(theses_DT.Enum_theses_DT.theses_type.ToString(), obj.theses_type);

        parms[5] = new SqlParameter(theses_DT.Enum_theses_DT.assigned_to.ToString(), obj.assigned_to);

        parms[6] = new SqlParameter(theses_DT.Enum_theses_DT.form_status.ToString(), obj.form_status);

        parms[7] = new SqlParameter(theses_DT.Enum_theses_DT.file_status.ToString(), obj.file_status);

        parms[8] = new SqlParameter(theses_DT.Enum_theses_DT.form_lock.ToString(), obj.form_lock);

        parms[9] = new SqlParameter(theses_DT.Enum_theses_DT.lock_files.ToString(), obj.lock_files);

        parms[10] = new SqlParameter(theses_DT.Enum_theses_DT.period_id.ToString(), obj.period_id);

        parms[11] = new SqlParameter(theses_DT.Enum_theses_DT.form_status_en.ToString(), obj.form_status_en);

        parms[12] = new SqlParameter(theses_DT.Enum_theses_DT.form_lock_en.ToString(), obj.form_lock_en);

        parms[13] = new SqlParameter(theses_DT.Enum_theses_DT.form_status_fr.ToString(), obj.form_status_fr);

        parms[14] = new SqlParameter(theses_DT.Enum_theses_DT.form_lock_fr.ToString(), obj.form_lock_fr);

        parms[15] = new SqlParameter(theses_DT.Enum_theses_DT.file_name.ToString(), obj.file_name);

        parms[16] = new SqlParameter(theses_DT.Enum_theses_DT.image_name.ToString(), obj.image_name);

        parms[17] = new SqlParameter(theses_DT.Enum_theses_DT.form_file.ToString(), obj.form_file);

        parms[18] = new SqlParameter(theses_DT.Enum_theses_DT.theses_date.ToString(), obj.theses_date);

        parms[19] = new SqlParameter(theses_DT.Enum_theses_DT.theses_hdate.ToString(), obj.theses_hdate);

        parms[20] = new SqlParameter(theses_DT.Enum_theses_DT.form_file_en.ToString(), obj.form_file_en);

        parms[21] = new SqlParameter(theses_DT.Enum_theses_DT.form_file_fr.ToString(), obj.form_file_fr);
        parms[22] = new SqlParameter(theses_DT.Enum_theses_DT.period_id_multi.ToString(), obj.period_id_multi);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(theses_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "theses_Save", parms);

             	    obj.id = Convert.ToInt32(parms[3].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int theses_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "theses_Delete", theses_ID);
                return theses_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "theses_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static theses_DT SelectByID(int theses_ID)
        {
            try
            {
              if (theses_ID > 0)
                {
                SqlDataReader drTableName;
                theses_DT oInfo_theses_DT = new theses_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "theses_Select", theses_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_theses_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_theses_DT;
               }
                else
                    return new theses_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

