//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		users_types_DB
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class users_types_DB
    {

        #region "Private methods"

        private static users_types_DT FillInfoObject(SqlDataReader dr)
        {

           users_types_DT obj_users_types_DT = new users_types_DT();

           
		obj_users_types_DT.id = Convert.ToInt32(dr[users_types_DT.Enum_users_types_DT.id.ToString()]);
		obj_users_types_DT.title = dr[users_types_DT.Enum_users_types_DT.title.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[users_types_DT.Enum_users_types_DT.title.ToString()]);

           return obj_users_types_DT;
        }

        private static SqlParameter[] GetParameters(users_types_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[2];
           
			
        

        parms[0] = new SqlParameter(users_types_DT.Enum_users_types_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(users_types_DT.Enum_users_types_DT.title.ToString(), obj.title);
            
            return parms;
        }

        #endregion

	#region "DB methods"

        public static int Save(users_types_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "users_types_Save", parms);
                return Convert.ToInt32(parms[0].Value);
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int users_types_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "users_types_Delete", users_types_ID);
                return users_types_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "users_types_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static users_types_DT SelectByID(int users_types_ID)
        {
            try
            {
                SqlDataReader drTableName;
                users_types_DT oInfo_users_types_DT = new users_types_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "users_types_Select", users_types_ID);
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_users_types_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_users_types_DT;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

