//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		WebSites_Template_details_DB
// Date Generated:	15-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Data.SqlClient;
using System.Data;


    public static class WebSites_Template_details_DB
    {

        #region "Private methods"

        private static WebSites_Template_details_DT FillInfoObject(SqlDataReader dr)
        {

           WebSites_Template_details_DT obj_WebSites_Template_details_DT = new WebSites_Template_details_DT();

           
		obj_WebSites_Template_details_DT.id = Convert.ToInt32(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.id.ToString()]);
		obj_WebSites_Template_details_DT.website_id = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.website_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.website_id.ToString()]);
		obj_WebSites_Template_details_DT.lang_id = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.lang_id.ToString()] == DBNull.Value ? 0 : Convert.ToInt32(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.lang_id.ToString()]);
		obj_WebSites_Template_details_DT.title = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.title.ToString()] == DBNull.Value ? null : Convert.ToString(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.title.ToString()]);
		obj_WebSites_Template_details_DT.describtion = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.describtion.ToString()] == DBNull.Value ? null : Convert.ToString(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.describtion.ToString()]);
		obj_WebSites_Template_details_DT.keywords = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.keywords.ToString()] == DBNull.Value ? null : Convert.ToString(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.keywords.ToString()]);
		obj_WebSites_Template_details_DT.notes = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.notes.ToString()] == DBNull.Value ? null : Convert.ToString(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.notes.ToString()]);
		obj_WebSites_Template_details_DT.responsible_name = dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.responsible_name.ToString()] == DBNull.Value ? string.Empty : Convert.ToString(dr[WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.responsible_name.ToString()]);

           return obj_WebSites_Template_details_DT;
        }

        private static SqlParameter[] GetParameters(WebSites_Template_details_DT obj)
        {
            SqlParameter[] parms = new SqlParameter[8];
           
			
        

        parms[0] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.id.ToString(), obj.id);
        parms[0].Direction = ParameterDirection.InputOutput;

        parms[1] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.website_id.ToString(), obj.website_id);

        parms[2] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.lang_id.ToString(), obj.lang_id);

        parms[3] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.title.ToString(), obj.title);

        parms[4] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.describtion.ToString(), obj.describtion);

        parms[5] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.keywords.ToString(), obj.keywords);

        parms[6] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.notes.ToString(), obj.notes);

        parms[7] = new SqlParameter(WebSites_Template_details_DT.Enum_WebSites_Template_details_DT.responsible_name.ToString(), obj.responsible_name);
            
            return parms;
        }

        #endregion

	    #region "DB methods"

        public static int Save(WebSites_Template_details_DT obj)
        {
            try
            {
                SqlParameter[] parms = GetParameters(obj);

                SqlHelper.ExecuteScalar(Database.ConnectionString, CommandType.StoredProcedure, "WebSites_Template_details_Save", parms);

             	    obj.id = Convert.ToInt32(parms[0].Value) ; 

           return obj.id ;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static int Delete(int WebSites_Template_details_ID)
        {
            try
            {
                SqlHelper.ExecuteNonQuery(Database.ConnectionString, "WebSites_Template_details_Delete", WebSites_Template_details_ID);
                return WebSites_Template_details_ID;
            }
            catch (Exception ex)
            {

                return -1;
            }
        }

        public static DataTable SelectAll()
        {
            try
            {
				 return SqlHelper.ExecuteDataset(Database.ConnectionString, "WebSites_Template_details_Select", 0).Tables[0];
		
            }
            catch (Exception ex)
            {

                return null;
            }
        }

        public static WebSites_Template_details_DT SelectByID(int WebSites_Template_details_ID , int lang_id)
        {
            try
            {
              if (WebSites_Template_details_ID > 0)
                {
                SqlDataReader drTableName;
                WebSites_Template_details_DT oInfo_WebSites_Template_details_DT = new WebSites_Template_details_DT();

                drTableName = SqlHelper.ExecuteReader(Database.ConnectionString, "WebSites_Template_details_Select", WebSites_Template_details_ID ,menus_update.get_current_lang ());
                if (drTableName != null)
                {
                    while (drTableName.Read())
                    {
                        oInfo_WebSites_Template_details_DT = FillInfoObject(drTableName);
                    }

                    drTableName.Close();
                }
                return oInfo_WebSites_Template_details_DT;
               }
                else
                    return new WebSites_Template_details_DT();
            }
            catch (Exception ex)
            {

                return null;
            }
        }
	#endregion


    }

