//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		achievements_details_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class achievements_details_DT
    {
        public enum Enum_achievements_details_DT
        {
            id, char_id, lang_id, details, title,date
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
        public Int32 char_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String details;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;

        public String date;
		
    }

