//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		artifacts_details_DT
// Date Generated:	14-06-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class artifacts_details_DT
    {
        public enum Enum_artifacts_details_DT
        {
            location, id, artifact_id, lang_id, related_char_type, form_pic_state, content_type, artifact_brief, artifact_details, notes, period_notes, title, maker_name, location_code, data_collector_name, data_revision_name, data_entry_name, save_org, save_org_no, related_event_type, related_objectives, related_obj_type, related_art_date, start_date, end_date, data_entry_revision_name, make_date, keywords, related_char_names, related_loc_type, related_event, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public String location;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 artifact_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 related_char_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_pic_state;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String artifact_brief;
		
		/// <summary>
		/// 
		/// </summary>
		public String artifact_details;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String period_notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
		/// <summary>
		/// 
		/// </summary>
		public String maker_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String location_code;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_collector_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String save_org;
		
		/// <summary>
		/// 
		/// </summary>
		public String save_org_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_event_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_objectives;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_obj_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_art_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String start_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String end_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String make_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String keywords;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_char_names;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_loc_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String related_event;
		
    }

