//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		artifacts_esnadat_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class artifacts_esnadat_DT
    {
        public enum Enum_artifacts_esnadat_DT
        {
            id, artifact_id, esnad_id, esnad_type, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 artifact_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 esnad_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 esnad_type;
		
    }

