//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		authors_details_DT
// Date Generated:	11-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class authors_details_DT
    {
        public enum Enum_authors_details_DT
        {
            details, id, author_id, lang_id, name, address, title, name_fromtitle, name_fromheader
        }

        
		/// <summary>
		/// 
		/// </summary>
		public String details;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 author_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String name;
		
		/// <summary>
		/// 
		/// </summary>
		public String address;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;

        public String name_fromtitle;

        public String name_fromheader;


		
    }

