//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		author_type_DT
// Date Generated:	16-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class author_type_DT
    {
        public enum Enum_author_type_DT
        {
            id, author_type, author_type_en, author_type_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_type_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_type_fr;
		
    }

