//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		awsema_DT
// Date Generated:	05-08-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class awsema_DT
    {
        public enum Enum_awsema_DT
        {
            id, char_id, type, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 char_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String type;
		
    }

