//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		char_admin_data_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class char_admin_data_DT
    {
        public enum Enum_char_admin_data_DT
        {
            id, char_id, entry_id, operation_date, role_ar, role_en, role_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 char_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 entry_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String operation_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String role_ar;
		
		/// <summary>
		/// 
		/// </summary>
		public String role_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String role_fr;
		
    }

