//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		content_status_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class content_status_DT
    {
        public enum Enum_content_status_DT
        {
            id, title, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
    }

