//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		content_images_types_DT
// Date Generated:	19-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class content_images_types_DT
    {
        public enum Enum_content_images_types_DT
        {
            id, title_ar, title_en, title_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_ar;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_fr;
		
    }

