//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		content_images_details_DT
// Date Generated:	08-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class content_images_details_DT
    {
        public enum Enum_content_images_details_DT
        {
            id, content_image_id, link_words, notes, period_desc, title, describtion, photographer, source, data_collector_name, data_revision_name, resource_name, presenter_details, lang_id, category, serial_no, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_image_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String link_words;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String period_desc;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
		/// <summary>
		/// 
		/// </summary>
		public String describtion;
		
		/// <summary>
		/// 
		/// </summary>
		public String photographer;
		
		/// <summary>
		/// 
		/// </summary>
		public String source;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_collector_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String resource_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String presenter_details;
		
		/// <summary>
		/// 
		/// </summary>
		public String lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String category;
		
		/// <summary>
		/// 
		/// </summary>
		public String serial_no;
		
    }

