//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		contents_notes_DT
// Date Generated:	02-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class contents_notes_DT
    {
        public enum Enum_contents_notes_DT
        {
            id, content_type, content_id, error_id, correction_done, usage_id, field_id, error_type, error_status, lang_id, error_place, observer_note, revision_note, observer_note_date, revision_note_date, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 error_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 correction_done;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 usage_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 field_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 error_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 error_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String error_place;
		
		/// <summary>
		/// 
		/// </summary>
		public String observer_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String revision_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String observer_note_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String revision_note_date;
		
    }

