//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		contents_errors_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class contents_errors_DT
    {
        public enum Enum_contents_errors_DT
        {
            id, content_type, form_file, error_name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_file;
		
		/// <summary>
		/// 
		/// </summary>
		public String error_name;
		
    }

