//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		contents_fields_DT
// Date Generated:	19-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class contents_fields_DT
    {
        public enum Enum_contents_fields_DT
        {
            id, content_type, translation, field_name, control_name, type, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 translation;
		
		/// <summary>
		/// 
		/// </summary>
		public String field_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String control_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String type;
		
    }

