//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		content_references_DT
// Date Generated:	27-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class content_references_DT
    {
        public enum Enum_content_references_DT
        {
            id, lang_id, content_type, content_id, content_type2, notes, title, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type2;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
    }

