//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		documents_DT
// Date Generated:	30-10-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class documents_DT
    {
        public enum Enum_documents_DT
        {
            highlight, highlight_panorama, id, publisher_id, pages_no, doc_type, content_type, assigned_to, lock_files, period_id, form_status_en, form_lock_en, form_status_fr, form_lock_fr, pages_from, pages_to, publish_or_not, form_status, file_status, form_lock, publish_no, folders_no, isbn, small_image, large_image, publish_date, creater, creater_no, publish_hdate, form_file, form_file_en, form_file_fr, period_id_multi
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 highlight;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 highlight_panorama;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 publisher_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pages_no;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 doc_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 assigned_to;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lock_files;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 period_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status_en;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock_en;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pages_from;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 pages_to;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 publish_or_not;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 file_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock;
		
		/// <summary>
		/// 
		/// </summary>
		public String publish_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String folders_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String isbn;
		
		/// <summary>
		/// 
		/// </summary>
		public String small_image;
		
		/// <summary>
		/// 
		/// </summary>
		public String large_image;
		
		/// <summary>
		/// 
		/// </summary>
		public String publish_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String creater;
		
		/// <summary>
		/// 
		/// </summary>
		public String creater_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String publish_hdate;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file_fr;

        public String period_id_multi;
        
		
    }

