//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		documents_types_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class documents_types_DT
    {
        public enum Enum_documents_types_DT
        {
            id, title, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
    }

