//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		esnad_type_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class esnad_type_DT
    {
        public enum Enum_esnad_type_DT
        {
            id, title, the_key, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
		/// <summary>
		/// 
		/// </summary>
		public String the_key;
		
    }

