//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		events_details_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class events_details_DT
    {
        public enum Enum_events_details_DT
        {
            id, event_id, lang_id, special_element, form_pic_state, event_brief, event_details, notes, link_words, title, data_collector_name, data_revision_name, data_entry_name, data_entry_revision_name, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 event_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 special_element;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_pic_state;
		
		/// <summary>
		/// 
		/// </summary>
		public String event_brief;
		
		/// <summary>
		/// 
		/// </summary>
		public String event_details;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String link_words;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_collector_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_revision_name;
		
    }

