//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		license_type_DT
// Date Generated:	16-05-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class license_type_DT
    {
        public enum Enum_license_type_DT
        {
            id, title_ar, title_en, title_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_ar;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_fr;
		
    }

