//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\nmsoltan using Mcit Generator
// Class Name:		manuscripts_details_DT
// Date Generated:	27-12-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class manuscripts_details_DT
    {
        public enum Enum_manuscripts_details_DT
        {
            id, manuscript_id, lang_id, period_id, keywords, notes, period_notes, title, author, title_src, author_src, man_lang, copy_place, author_intro, author_mosk, title_fromtitle, title_intro, title_mosk, listinging, data_collector_name, data_revision_name, data_entry_name, data_entry_revision_name, author_fromtitle, license_type, oldest_license_date, oldest_license_date_m, oldest_license_date_h, listinging_date_m, listinging_date_h, country, town, general_no, special_no, the_art, special_lib, ruler, copy_contains, font_type, copy_has, introduction, conclusion, papers_to, parts_no, folders_no, height, length, width, copier, copy_date, copy_date_type, copy_state, collection_no, papers_from 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 manuscript_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 period_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String keywords;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String period_notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
		/// <summary>
		/// 
		/// </summary>
		public String author;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_src;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_src;
		
		/// <summary>
		/// 
		/// </summary>
		public String man_lang;
		
		/// <summary>
		/// 
		/// </summary>
		public String copy_place;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_intro;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_mosk;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_fromtitle;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_intro;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_mosk;
		
		/// <summary>
		/// 
		/// </summary>
		public String listinging;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_collector_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String author_fromtitle;
		
		/// <summary>
		/// 
		/// </summary>
		public String license_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String oldest_license_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String oldest_license_date_m;
		
		/// <summary>
		/// 
		/// </summary>
		public String oldest_license_date_h;
		
		/// <summary>
		/// 
		/// </summary>
		public String listinging_date_m;
		
		/// <summary>
		/// 
		/// </summary>
		public String listinging_date_h;
		
		/// <summary>
		/// 
		/// </summary>
		public String country;
		
		/// <summary>
		/// 
		/// </summary>
		public String town;
		
		/// <summary>
		/// 
		/// </summary>
		public String general_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String special_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String the_art;
		
		/// <summary>
		/// 
		/// </summary>
		public String special_lib;
		
		/// <summary>
		/// 
		/// </summary>
		public String ruler;
		
		/// <summary>
		/// 
		/// </summary>
		public String copy_contains;
		
		/// <summary>
		/// 
		/// </summary>
		public String font_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String copy_has;
		
		/// <summary>
		/// 
		/// </summary>
		public String introduction;
		
		/// <summary>
		/// 
		/// </summary>
		public String conclusion;
		
		/// <summary>
		/// 
		/// </summary>
		public String papers_to;
		
		/// <summary>
		/// 
		/// </summary>
		public String parts_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String folders_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String height;
		
		/// <summary>
		/// 
		/// </summary>
		public String length;
		
		/// <summary>
		/// 
		/// </summary>
		public String width;
		
		/// <summary>
		/// 
		/// </summary>
		public String copier;
		
		/// <summary>
		/// 
		/// </summary>
		public String copy_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String copy_date_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String copy_state;
		
		/// <summary>
		/// 
		/// </summary>
		public String collection_no;
		
		/// <summary>
		/// 
		/// </summary>
		public String papers_from;

		
		
    }

