//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_restoration_DT
// Date Generated:	11-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class places_restoration_DT
    {
        public enum Enum_places_restoration_DT
        {
            id, place_id, restoration_age, restoration_participants, restoration_participants_en, restoration_participants_fr, restoration_desc, restoration_desc_en, restoration_desc_fr, restoration_note, restoration_georg_date, restoration_hijri_date, restoration_person, restoration_person_en, restoration_person_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 place_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 restoration_age;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_participants;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_participants_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_participants_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_desc;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_desc_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_desc_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_georg_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_hijri_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_person;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_person_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_person_fr;
		
    }

