//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_details_DT
// Date Generated:	25-03-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class places_details_DT
    {
        public enum Enum_places_details_DT
        {
            id, place_id, main_architectural_styles_type, current_function, lang_id, form_pic_state, brief, description, notes, link_words, literature, geometric, current_location_note, current_address_notes, current_state, restoration_current_state, restoration_current_state_participants, restoration_current_state_note, current_location_desc, floral, main_architectural_styles_type_general_feature, main_architectural_styles_type_notes, current_function_notes, current_address, current_address_desc, name, outside_entrances, outside_interfaces, outside_windows, outside_minarets, outside_domes, data_collector_name, data_revision_name, data_entry_name, data_entry_revision_name, inside_sabeel_room, main_architectural_styles_type_other, current_function_other, restoration_current_state_person, current_location_longitude, current_location_latitude, inside_yard, inside_roofs, inside_iwans, inside_halls, inside_seats, inside_supplements, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 place_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 main_architectural_styles_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 current_function;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_pic_state;
		
		/// <summary>
		/// 
		/// </summary>
		public String brief;
		
		/// <summary>
		/// 
		/// </summary>
		public String description;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String link_words;
		
		/// <summary>
		/// 
		/// </summary>
		public String literature;
		
		/// <summary>
		/// 
		/// </summary>
		public String geometric;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_location_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_address_notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_state;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_current_state;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_current_state_participants;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_current_state_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_location_desc;
		
		/// <summary>
		/// 
		/// </summary>
		public String floral;
		
		/// <summary>
		/// 
		/// </summary>
		public String main_architectural_styles_type_general_feature;
		
		/// <summary>
		/// 
		/// </summary>
		public String main_architectural_styles_type_notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_function_notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_address;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_address_desc;
		
		/// <summary>
		/// 
		/// </summary>
		public String name;
		
		/// <summary>
		/// 
		/// </summary>
		public String outside_entrances;
		
		/// <summary>
		/// 
		/// </summary>
		public String outside_interfaces;
		
		/// <summary>
		/// 
		/// </summary>
		public String outside_windows;
		
		/// <summary>
		/// 
		/// </summary>
		public String outside_minarets;
		
		/// <summary>
		/// 
		/// </summary>
		public String outside_domes;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_collector_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_entry_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_sabeel_room;
		
		/// <summary>
		/// 
		/// </summary>
		public String main_architectural_styles_type_other;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_function_other;
		
		/// <summary>
		/// 
		/// </summary>
		public String restoration_current_state_person;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_location_longitude;
		
		/// <summary>
		/// 
		/// </summary>
		public String current_location_latitude;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_yard;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_roofs;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_iwans;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_halls;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_seats;
		
		/// <summary>
		/// 
		/// </summary>
		public String inside_supplements;
		
    }

