//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_DT
// Date Generated:	15-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class places_DT
    {
        public enum Enum_places_DT
        {
            highlight, highlight_panorama, id, place_type, assigned_to, form_status, file_status, form_lock, lock_files, form_status_en, form_lock_en, form_status_fr, form_lock_fr, rblFormImage, image_name, place_type_another, creation_georg_date, creation_hijr_date, end_creation_georg_date, end_creation_hijr_date, form_file, form_file_en, form_file_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 highlight;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 highlight_panorama;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 place_type;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 assigned_to;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 file_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lock_files;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status_en;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock_en;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 rblFormImage;
		
		/// <summary>
		/// 
		/// </summary>
		public String image_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String place_type_another;
		
		/// <summary>
		/// 
		/// </summary>
		public String creation_georg_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String creation_hijr_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String end_creation_georg_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String end_creation_hijr_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file_fr;
		
    }

