//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_building_material_DT
// Date Generated:	25-03-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class places_building_material_DT
    {
        public enum Enum_places_building_material_DT
        {
            id, place_id, building_raw_material, building_raw_material_use, building_raw_material_notes, building_raw_material_other, building_raw_material_use_other, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 place_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 building_raw_material;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 building_raw_material_use;
		
		/// <summary>
		/// 
		/// </summary>
		public String building_raw_material_notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String building_raw_material_other;
		
		/// <summary>
		/// 
		/// </summary>
		public String building_raw_material_use_other;
		
    }

