//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		places_names_DT
// Date Generated:	10-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class places_names_DT
    {
        public enum Enum_places_names_DT
        {
            id, place_id, name_age, name_in_age, name_note, name_age_en, name_age_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 place_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 name_age;
		
		/// <summary>
		/// 
		/// </summary>
		public String name_in_age;
		
		/// <summary>
		/// 
		/// </summary>
		public String name_note;
		
		/// <summary>
		/// 
		/// </summary>
		public String name_age_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String name_age_fr;
		
    }

