//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\maelalfy using Mcit Generator
// Class Name:		raw_material_use_DT
// Date Generated:	23-04-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class raw_material_use_DT
    {
        public enum Enum_raw_material_use_DT
        {
            id, title_ar, title_en, title_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_ar;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_fr;
		
    }

