//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		styles_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class styles_DT
    {
        public enum Enum_styles_DT
        {
            id, content_type, title_ar, title_en, title_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_ar;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_fr;
		
    }

