//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		takreezat_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class takreezat_DT
    {
        public enum Enum_takreezat_DT
        {
            id, char_id, type, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 char_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String type;
		
    }

