//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		takreezat_details_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class takreezat_details_DT
    {
        public enum Enum_takreezat_details_DT
        {
            id, takreezat_id, lang_id, details, title, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 takreezat_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String details;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
    }

