//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		tamalokat_DT
// Date Generated:	24-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class tamalokat_DT
    {
        public enum Enum_tamalokat_DT
        {
            id, manuscript_id, tmlkat_name, tmlkat_date, tmlkat_date_type, tmlkat_name_en, tmlkat_name_fr, notes
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 manuscript_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String tmlkat_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String tmlkat_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String tmlkat_date_type;
		
		/// <summary>
		/// 
		/// </summary>
		public String tmlkat_name_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String tmlkat_name_fr;

        public String notes;
    }

