//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		theses_details_DT
// Date Generated:	11-03-2014
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class theses_details_DT
    {
        public enum Enum_theses_details_DT
        {
            id, these_id, lang_id, form_pic_state, theses_no, theses_lang2, keywords, notes, title, author, searcher_name, supervisor_name, theses_lang, supervisor_name1, data_collector_name, data_revision_name, supervisor_name2, theses_date, theses_hdate, unversity, collage, section, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 these_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lang_id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_pic_state;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 theses_no;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 theses_lang2;
		
		/// <summary>
		/// 
		/// </summary>
		public String keywords;
		
		/// <summary>
		/// 
		/// </summary>
		public String notes;
		
		/// <summary>
		/// 
		/// </summary>
		public String title;
		
		/// <summary>
		/// 
		/// </summary>
		public String author;
		
		/// <summary>
		/// 
		/// </summary>
		public String searcher_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String supervisor_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String theses_lang;
		
		/// <summary>
		/// 
		/// </summary>
		public String supervisor_name1;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_collector_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String data_revision_name;
		
		/// <summary>
		/// 
		/// </summary>
		public String supervisor_name2;
		
		/// <summary>
		/// 
		/// </summary>
		public String theses_date;
		
		/// <summary>
		/// 
		/// </summary>
		public String theses_hdate;
		
		/// <summary>
		/// 
		/// </summary>
		public String unversity;
		
		/// <summary>
		/// 
		/// </summary>
		public String collage;
		
		/// <summary>
		/// 
		/// </summary>
		public String section;
		
    }

