//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\arezk using Mcit Generator
// Class Name:		timeline_dates_types_DT
// Date Generated:	20-02-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class timeline_dates_types_DT
    {
        public enum Enum_timeline_dates_types_DT
        {
            id, content_type_id, title_ar, title_en, title_fr, 
        }

        
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 content_type_id;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_ar;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String title_fr;
		
    }

