//////////////////////////////////////////////////////////////////////////////////////////
// Generated By:	MCIT\hdarwish using Mcit Generator
// Class Name:		topics_DT
// Date Generated:	05-07-2012
//////////////////////////////////////////////////////////////////////////////////////////
using System;



    public class topics_DT
    {
        public enum Enum_topics_DT
        {
            highlight, id, assigned_to, form_status, file_status, form_lock, lock_files, form_status_en, form_lock_en, form_status_fr, form_lock_fr, small_image, large_image, form_file, form_file_en, form_file_fr, rblFormImage
        }

        /// <summary>
        /// 
        /// </summary>
        public Int32 rblFormImage;

		/// <summary>
		/// 
		/// </summary>
		public Int32 highlight;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 id;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 assigned_to;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 file_status;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 lock_files;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status_en;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock_en;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_status_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public Int32 form_lock_fr;
		
		/// <summary>
		/// 
		/// </summary>
		public String small_image;
		
		/// <summary>
		/// 
		/// </summary>
		public String large_image;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file_en;
		
		/// <summary>
		/// 
		/// </summary>
		public String form_file_fr;
		
    }

